const translations = {
    uz: {
        toastWarning: "Tizim xavfsizligi tufayli kodni ko'rish taqiqlanadi!",
        schoolName: "Xo'jayli tumani ixtisoslashtirilgan maktabi",
        welcomeMsg: "Xush kelibsiz! Testga kirish uchun ma'lumotlarni kiriting.",
        namePlaceholder: "F.I.SH.",
        classPlaceholder: "Sinf / Guruh (Masalan: 9-A, 11-B)",
        pinPlaceholder: "Maxsus kod (PIN)",
        cogKnowing: "Bilish",
        cogApp: "Qo'llash",
        cogReasoning: "Mulohaza qilish",
        selClass: "Sinfni tanlang",
        selQuarter: "Chorakni tanlang",
        btnExportExcel: "Excel formatda yuklash (BSB/CHSB)",
        startBtn: "Kirish",
        adminLoginBtn: "Admin paneliga kirish",
        leaderboardTitle: "Top-10 Reyting",
        thRank: "O'rin",
        thName: "F.I.SH.",
        thClass: "Sinf",
        thPoints: "Ball",
        thTime: "Vaqt",
        adminModalTitle: "Admin tizimiga kirish",
        adminPassPlaceholder: "Admin parolini kiriting",
        adminModalSubmit: "Kirish",
        adminModalCancel: "Bekor qilish",
        incorrectPass: "Noto'g'ri parol!",
        adminPanelTitle: "Admin boshqaruv paneli",
        adminLogoutBtn: "Panelni yopish",
        tabQuestions: "Savollar boshqaruvi",
        tabResults: "O'quvchilar natijalari",
        tabSettings: "Sozlamalar",
        tabQr: "QR-kod olish",
        tabSecurity: "Xavfsizlik",
        secTitle: "Xavfsizlik Sozlamalari",
        secShowAnswersTitle: "Natijalarda javoblarni ko'rsatish",
        secShowAnswersDesc: "Test yakunida o'quvchi xato qilgan savollarning to'g'ri javoblari ro'yxatini ko'ra oladimi?",
        hiddenAnswersMsg: "Xavfsizlik nuqtai nazaridan to'g'ri javoblar yashirilgan.",
        settingsTeachersTitle: "O'qituvchilar uchun vaqtinchalik ruxsatnomalar",
        settingsTeachersHint: "O'qituvchilar o'z faniga savol qo'shishi va natijalarni ko'rishi uchun vaqtinchalik parol (token) yarating.",
        lblTeacherName: "O'qituvchi F.I.SH:",
        lblTeacherSubject: "Fanni tanlang:",
        lblTeacherExpire: "Amal qilish muddati:",
        exp2h: "2 soat",
        exp1d: "1 kun",
        exp1w: "1 hafta",
        exp1m: "1 oy",
        btnGenerateToken: "Parol yaratish",
        thTeacherName: "F.I.SH.",
        thTeacherSubject: "Fan",
        thTeacherToken: "Parol",
        thTeacherExpire: "Tugash vaqti",
        thTeacherAction: "Amal",
        alertTokenExpired: "Ushbu parolning amal qilish muddati tugagan!",
        manualAddTitle: "Yangi savol qo'shish (Qo'lda)",
        qTextPlaceholder: "Savol matni",
        optAPlaceholder: "Variant A",
        optBPlaceholder: "Variant B",
        optCPlaceholder: "Variant C",
        optDPlaceholder: "Variant D",
        lblCorrect: "To'g'ri javob:",
        optA: "Variant A",
        optB: "Variant B",
        optC: "Variant C",
        optD: "Variant D",
        lblPoints: "Savol balli:",
        saveQBtn: "Savolni saqlash",
        wordImportTitle: "Word fayldan yuklash (.docx)",
        wordImportHint: "Word faylingiz quyidagi shablonga mos bo'lishi kerak:",
        btnImport: "Savollarni import qilish",
        questionsListTitle: "Mavjud savollar",
        resultsTableTitle: "Natijalar jadvali",
        lblFilterClass: "Sinf bo'yicha filter:",
        filterAll: "Barchasi",
        btnExportCsv: "Excel formatda yuklab olish (CSV)",
        btnClearResults: "Barcha natijalarni tozalash",
        thScore: "To'plangan ball",
        thPercent: "Foiz",
        thBlocks: "Bloklar soni",
        settingsGeneralTitle: "Test umumiy sozlamalari",
        lblTestDuration: "Test vaqti (daqiqada):",
        settingsTelegramTitle: "Sozlamalar",
        settingsTelegramHint: "Har bir o'quvchi testni tugatgandan so'ng, uning natijalari Telegram orqali sizga yuboriladi.",
        lblTgBotToken: "Telegram Bot Token:",
        lblTgChatId: "Telegram Chat ID (Guruh yoki shaxsiy ID):",
        btnSaveSettings: "Barcha sozlamalarni saqlash",
        qrTitle: "Loyiha QR-kodi",
        qrHint: "Ushbu QR-kod yordamida o'quvchilar testga tezkor kirishlari mumkin.",
        downloadQr: "QR-kodni yuklab olish (PNG)",
        quizInfoQuestion: "Savol",
        quizInfoPoints: "ball",
        nextBtn: "Keyingi savol",
        testFinishedTitle: "Test Yakunlandi",
        certCongrats: "Tabriklaymiz! Siz yuqori natija ko'rsatdingiz.",
        certInfo: "Siz o'z sertifikatingizni yuklab olishingiz mumkin.",
        btnDownloadCert: "Sertifikatni yuklab olish (PNG)",
        errorReviewTitle: "Xatolar ustida ishlash",
        btnBackToHome: "Asosiy sahifaga qaytish",
        lockWarningTitle: "SIZ BLOKLANDINGIZ!",
        lockWarningText: "Tizimdan foydalanish qoidalari buzildi (ekran o'zgartirildi yoki to'liq ekran rejimidan chiqildi).",
        lockAdminNote: "Siz test qoidalarini buzgansiz! Testni davom ettirish uchun o'qituvchi parolini kiriting:",
        lockPassPlaceholder: "O'qituvchi paroli",
        lockBtnUnlock: "Ochish",
        lblUnblockPin: "Blokdan chiqarish paroli:",
        
        // JS specific
        alertDuration: "Iltimos, test vaqtini to'g'ri kiriting!",
        teacherPinSaved: "Faningiz uchun sozlamalar muvaffaqiyatli saqlandi!",
        teacherTimerPrefix: "Sizning ruxsatnomangiz tugashiga qoldi:",
        teacherTimerMins: "daqiqa",
        teacherTimerSecs: "soniya",
        adminLoginLink: "O'qituvchilar va Admin kirishi",
        backToStudentLogin: "O'quvchi oynasiga qaytish",
        teacherPinSetterTitle: "Faningiz uchun PIN-kod va Test vaqtini belgilang",
        lblTeacherPin: "O'quvchilar uchun PIN-kod:",
        lblTeacherDuration: "Test davomiyligi (daqiqa):",
        btnSaveTeacherSettings: "Sozlamalarni saqlash",
        timeUpAlert: "Sizning vaqtinchalik ruxsatnomangiz o'z nihoyasiga yetdi!",
        alertDetails: "Iltimos, ismingiz va sinfingizni to'liq kiriting!",
        alertNoQuestions: "Savollar mavjud emas! Iltimos, admin bilan bog'laning.",
        alertFields: "Barcha maydonlarni to'ldiring!",
        alertAdded: "Savol qo'shildi!",
        alertSelectFile: "Iltimos, avval Word (.docx) faylini tanlang!",
        alertReadError: "Faylni o'qishda xatolik yuz berdi!",
        alertConfirmClear: "Natijalarni butunlay o'chirmoqchimisiz?",
        alertNoExport: "Eksport qilish uchun natijalar mavjud emas!",
        alertImportEmpty: "Fayl ichidan mos formatdagi savollar topilmadi! Iltimos shablonni tekshiring.",
        alertConfirmDelete: "Ushbu savolni o'chirib tashlamoqchimisiz?",
        alertTimeout: "Vaqt tugadi! Test avtomatik yakunlanadi.",
        alertImportSuccess: "Muvaffaqiyatli yuklandi:",
        alertImportSuccess2: "ta yangi savol qo'shildi!",
        btnDelete: "O'chirish",
        unknown: "Noma'lum",
        times: "marta",
        noResults: "Hozircha natijalar mavjud emas.",
        emptyLeaderboard: "Reyting jadvali bo'sh.",
        notAnswered: "Javob berilmagan",
        yourAnswer: "Siz tanlagan javob:",
        noMistakes: "Tabriklaymiz! Hech qanday xatoga yo'l qo'yilmadi.",
        studentLabel: "Talaba:",
        percentageLabel: "Foiz ko'rsatkichi:",
        timeSpent: "Sarflangan vaqt:",
        violations: "Qoidabuzarliklar (Bloklar):",
        analysisLabel: "Tahlil:",
        totalLimit: "Jami limit:",
        min: "daq",
        certTitle: "MAQTOV YORLIG'I",
        certGivenTo: "Ushbu sertifikat topshiriladi:",
        studentOfClass: "-sinf o'quvchisi",
        certText1: "Portalimizdagi imtihondan yuqori natija",
        certText2: "maxsus fanlar bo'yicha mustahkam bilimini namoyon etganligi uchun.",
        dateLabel: "Sana:",
        portalAdmin: "Portal Ma'muriyati",
        examResult: "IMTIHON NATIJASI",
        analysisEx: "A'lo daraja! Siz mavzuni mukammal o'zlashtirgansiz.",
        analysisGood: "Yaxshi natija. Bilimingizni yanada mustahkamlashingiz mumkin.",
        analysisSat: "Qoniqarli. Takrorlash ko'proq talab etiladi.",
        analysisBad: "Past natija. Iltimos, darslikni qaytadan o'qib chiqing.",
        lblFilterQuarter: "Chorak:",
        qAll: "Barcha choraklar",
        q1: "I chorak",
        q2: "II chorak",
        q3: "III chorak",
        q4: "IV chorak",
        analyticsTitle: "Choraklik Tahlil (Kognitiv darajalar)",
        lblCognitive: "Kognitiv daraja:",
        statTotalStudents: "O'quvchilar soni",
        statAvgScore: "O'rtacha ko'rsatkich (%)",
        statQuality: "Sifat ko'rsatkichi (70%+)",
        lblQFormat: "Savol formati:",
        fmtClosed: "Yopiq test (A,B,C,D)",
        fmtOpen: "Ochiq savol (Yozma)",
        lblOpenAnswer: "To'g'ri javob matni (Kalit so'z):",
        phOpenAnswer: "Javobingizni kiriting...",
        lblWritten: "Yozma",
        comparisonTitle: "Ikki chorakni o'zaro tahlil qilish",
        btnCompare: "Tahlil qilish",
        compIncreased: "ga O'SDI",
        compDecreased: "ga PASAYDI",
        compSame: "O'ZGARISHSZ qoldi",
        compConclusion: "Pedagogik tahlil:",
        compConclusionGood: "Yaxshi natija, qo'shimcha darslar o'z samarasini bermoqda.",
        compConclusionBad: "Xavotirli holat, o'zlashtirish tushib ketgan. Qo'shimcha chora-tadbirlar ko'rish zarur.",
        compConclusionNeutral: "O'zlashtirish barqaror, ammo o'sish ustida ishlash tavsiya etiladi",
        subjectPlaceholder: "Fanni tanlang",
        subjOnaTili: "Ona tili",
        subjMatematika: "Matematika",
        subjFizika: "Fizika",
        subjKimyo: "Kimyo",
        subjBiologiya: "Biologiya",
        subjTarix: "Tarix",
        subjHuquq: "Huquq",
        subjInformatika: "Informatika",
        settingsPinsTitle: "Fanlar va PIN-kodlar",
        settingsPinsHint: "O'quvchilar testni boshlashi uchun har bir fanga maxsus PIN-kod o'rnating.",
        settingsGeminiTitle: "Gemini AI Sozlamalari",
        settingsGeminiHint: "Pedagogik tahlil o'tkazish uchun Google Gemini API kalitini kiriting.",
        lblGeminiKey: "Gemini AI API Kaliti:",
        btnAnalyzeAI: "Gemini AI tahlili",
        aiAnalyzing: "Gemini AI sinf natijalari va kognitiv darajalarni tahlil qilmoqda...",
        btnCloseAI: "Natijani yopish",
        lblTargetClass: "Mo'ljallangan sinf:",
        alertNoClassTest: "Ushbu sinf uchun test topilmadi!",
        lblSelectStudent: "O'quvchini tanlang:",
        selStudent: "O'quvchini tanlang...",
        btnViewDetails: "Batafsil ko'rish",
        btnCloseDetails: "Yopish",
        lblCorrectAnswer: "To'g'ri javob",
        lblStudentAnswer: "O'quvchi javobi",
        aiAnalysisTitle: "Gemini AI Tahlili",
        thSubject: "Fan",
        alertWrongPin: "Xato! Bu fan uchun PIN-kod noto'g'ri kiritildi.",
        alertGeminiNoKey: "Xato! Iltimos, Sozlamalar bo'limidan Gemini API kalitini kiriting.",
        geminiLoading: "Gemini AI tahlil qilmoqda, iltimos kuting...",
        lblTestType: "Test turi:",
        testTypeBSB: "BSB",
        testTypeCHSB: "CHSB",
        lblUploadImage: "Rasm yuklash",
        instructionRules: "Test ishlash qoidalari:",
        rule1: "Testni boshlagandan so'ng vaqt ortga hisoblana boshlaydi.",
        rule2: "Sahifani yangilash (Refresh) yoki yopish taqiqlanadi (natija yo'qolishi mumkin).",
        rule3: "Yopiq testlarda faqat bitta to'g'ri javobni belgilang, ochiq savollarda esa javobni klaviaturada qo'lda yozing.",
        btnBeginTest: "Testni boshlash",
        lblTime: "Vaqt:",
        lblCount: "Savollar soni:",
        adminLogout: "Chiqish",
        tabQR: "QR Kod",
        addQTitle: "Qo'lda Savol Qo'shish",
        lblCorrectAns: "To'g'ri:",
        btnAddQuestion: "Savolni Qo'shish",
        wordUploaderTitle: "Word (Docx) yuklash",
        wordUploaderInfo: "Fayl quyidagi qat'iy formatda bo'lishi shart:",
        btnUploadWord: "Bazaga qo'shish",
        dbQuestionsTitle: "Bazada:",
        dbQuestionsCount: "ta savol",
        teacherTokensTitle: "O'qituvchilar uchun vaqtinchalik ruxsatnomalar",
        teacherTokensHint: "O'qituvchilarga faqat o'z fanini boshqarish huquqini beruvchi vaqtinchalik parollar (tokenlar) yarating.",
        lblDefaultTime: "Standart Test davomiyligi (daqiqa):",
        settingsTgHint: "O'quvchi testni yakunlaganda, natija avtomatik ravishda telegram bot yoki guruhga yuboriladi.",
        lblTgToken: "Bot Token:",
        lblTgChatId: "Chat ID (yoki Guruh ID):",
        secAnswersTitle: "Test Javoblari (O'quvchiga)",
        secAnswersLabel: "Test yakunida to'g'ri javoblarni o'quvchiga ko'rsatish:",
    btnShowAnswersOn: "Javoblarni ko'rsatish: YOQILGAN",
    btnShowAnswersOff: "Javoblarni ko'rsatish: O'CHIRILGAN",
        secAnswersHint: "Xavfsizlik nuqtai nazaridan to'g'ri javoblar yashirilgan.",
        qrCodeTitle: "Platforma uchun QR Kod",
        qrCodeHint: "Ushbu QR kod orqali o'quvchilar testga tez va oson kirishlari mumkin.",
        btnDownloadQR: "QR Kodni Yuklab Olish (PNG)",
        phQuestionText: "Savol matnini bu yerga yozing...",
        phOptA: "A varianti...",
        phOptB: "B varianti...",
        phOptC: "C varianti...",
        phOptD: "D varianti...",
        lblAdminQuarter: "Chorak:",
        settingsSavedMsg: "Barcha sozlamalar saqlandi!",
        alertFillFields: "Barcha maydonlarni to'ldiring!",
        confirmDeleteQ: "Ushbu savolni o'chirmoqchimisiz?",
        confirmClearResults: "Natijalarni butunlay o'chirmoqchimisiz?",
        msgResultsCleared: "Natijalar tozalandi!",
        msgQuestionDeleted: "Savol o'chirildi!",
        btnFinishQuiz: "Yakunlash",
        thPercentage: "Foiz",
        thDate: "Sana",
        alertGeminiKey: "Gemini API kaliti sozlanmagan! Sozlamalar bo'limidan kiriting.",
        tempPasswordExpired: "Vaqtinchalik parol muddati tugagan!",
        thExpireDate: "Amal qilish muddati:",
        currentActiveToken: "Joriy vaqtinchalik parol:",
        noActiveToken: "Faol vaqtinchalik parol mavjud emas"
      },
      qq: {
        toastWarning: "Sistema qawipsizligi sebepli kodti kГіriw qadaЗµalanadД±!",
        schoolName: "Xojeli rayonД± qГЎnigelestirilgen mektebi",
        welcomeMsg: "Xosh keldiЕ„iz! Testke kiriw ushД±n maЗµlД±wmatlardД± kiritiЕ„.",
        namePlaceholder: "OqД±wshД±nД±Е„ F.A.ГЃ.",
        classPlaceholder: "SД±nД±p / Gruppa (MД±salД±: 9-A, 11-B)",
        pinPlaceholder: "PIN-kodtД± kiritiЕ„",
        cogKnowing: "Biliw",
        cogApp: "Qollaw",
        cogReasoning: "Pikirlew",
        selClass: "KlastД± taЕ„laЕ„",
        selQuarter: "Sherekti taЕ„laЕ„",
        btnExportExcel: "Excel formatД±nda jГєklew (I-ShSB)",
        startBtn: "Kiriw",
        adminLoginBtn: "Admin paneline kiriw",
        leaderboardTitle: "рџЏ† Top-10 Reyting",
        thRank: "OrД±n",
        thName: "OqД±wshД±nД±Е„ F.A.ГЃ.",
        thClass: "Klass",
        thPoints: "Ball",
        thTime: "WaqД±t",
        adminModalTitle: "Admin sistemasД±na kiriw",
        adminPassPlaceholder: "Admin parolД±n kiritiЕ„",
        adminModalSubmit: "Kiriw",
        adminModalCancel: "Biykarlaw",
        incorrectPass: "NadurД±s parol!",
        adminPanelTitle: "Admin basqarД±w paneli",
        adminLogoutBtn: "Paneldi jabД±w",
        tabQuestions: "Sorawlar basqarД±wД±",
        tabResults: "OqД±wshД±lar nГЎtiyjeleri",
        tabSettings: "Sazlamalar",
        tabQr: "QR-kod alД±w",
        tabSecurity: "QГЎwipsizlik",
        secTitle: "QГЎwipsizlik sazlamalarД±",
        secShowAnswersTitle: "NГЎtiyjelerde juwaptД± kГіrsetiw",
        secShowAnswersDesc: "Test juwmaqlarД±nda oqД±wshД± qГЎtelik qД±lЗµan sorawlardД±Е„ durД±s juwaplarД± dizimin kГіre alama?",
        hiddenAnswersMsg: "QГЎwipsizlik kГіzqarasД±nan durД±s juwaplar jasД±rД±lЗµan.",
        settingsTeachersTitle: "OqД±wshД±lar ushД±n waqtД±nshalД±q ruqsatnamalar",
        settingsTeachersHint: "OqД±wshД±lar Гіz pГЎnine soraw qosД±wД± hГЎm nГЎtiyjelerdi kГіriwi ushД±n waqtД±nshalД±q parol (token) jaratД±Е„.",
        lblTeacherName: "OqД±wshД± F.A.A:",
        lblTeacherSubject: "PГЎndi taЕ„laЕ„:",
        lblTeacherExpire: "ГЃmel qД±lД±w mГєddeti:",
        exp2h: "2 saat",
        exp1d: "1 kГєn",
        exp1w: "1 hГЎpte",
        exp1m: "1 ay",
        btnGenerateToken: "Parol jaratД±w",
        thTeacherName: "F.A.A.",
        thTeacherSubject: "PГЎn",
        thTeacherToken: "Parol",
        thTeacherExpire: "JuwmaqlanД±w waqtД±",
        thTeacherAction: "ГЃmel",
        alertTokenExpired: "Bul paroldД±Е„ ГЎmel qД±lД±w mГєddeti tawsД±lЗµan!",
        manualAddTitle: "JaЕ„a soraw qosД±w (Qoldan)",
        qTextPlaceholder: "Soraw teksti",
        optAPlaceholder: "Variant A",
        optBPlaceholder: "Variant B",
        optCPlaceholder: "Variant C",
        optDPlaceholder: "Variant D",
        lblCorrect: "DurД±s juwap:",
        optA: "Variant A",
        optB: "Variant B",
        optC: "Variant C",
        optD: "Variant D",
        lblPoints: "Soraw balД±:",
        saveQBtn: "SorawdД± saqlaw",
        wordImportTitle: "Word fayldan juklew (.docx)",
        wordImportHint: "Word faylД±Е„Д±z tГіmendegi shablonЗµa sГЎykes keliwi kerek:",
        btnImport: "SorawlardД± import qД±lД±w",
        questionsListTitle: "BarlД±q sorawlar",
        resultsTableTitle: "NГЎtiyjeler kestesi",
        lblFilterClass: "Klass boyД±nsha filter:",
        filterAll: "BarlД±ЗµД±",
        btnExportCsv: "Excel formatД±nda juklep alД±w (CSV)",
        btnClearResults: "BarlД±q natiyjelerdi tazalaw",
        thScore: "ToplanЗµan ball",
        thPercent: "Procent",
        thBlocks: "Bloklar sanД±",
        settingsGeneralTitle: "Test ulД±wma sazlamalarД±",
        lblTestDuration: "Test waqtД± (minutta):",
        settingsTelegramTitle: "Sazlamalar",
        settingsTelegramHint: "HГЎr bir oqД±wshД± testti juwmaqlaЗµannan keyin, onД±Е„ natiyjeleri Telegram arqalД± sizge jiberiledi.",
        lblTgBotToken: "Telegram Bot Token:",
        lblTgChatId: "Telegram Chat ID (Gruppa yamasa jeke ID):",
        alertSaved: "BarlД±q sazlamalar saqlandД±!",
        btnSaveSettings: "BarlД±q sazlamalardД± saqlaw",
        qrTitle: "Proekt QR-kodД±",
        qrHint: "UsД± QR-kod jГЎrdeminde oqД±wshД±lar testke tez kiriwi mГєmkin.",
        downloadQr: "QR-kodtД± juklep alД±w (PNG)",
        quizInfoQuestion: "Soraw",
        quizInfoPoints: "ball",
        nextBtn: "Keyingi soraw",
        testFinishedTitle: "Test JuwmaqlandД±",
        certCongrats: "QutlД±qlaymД±z! Siz joqarД± nГЎtiyje kГіrsettiЕ„iz.",
        certInfo: "Siz Гіz sertifikatД±Е„Д±zdД± jГєklep alД±wД±Е„Д±z mГєmkin.",
        btnDownloadCert: "SertifikattД± juklep alД±w (PNG)",
        errorReviewTitle: "QГЎteler Гєstinde islew",
        btnBackToHome: "TiykarЗµД± betke qaytД±w",
        lockWarningTitle: "SД°Z BLOKLANDIЕѓIZ!",
        lockWarningText: "Sistemadan paydalanД±w qaЗµД±ydalarД± buzД±ldД± (ekran Гіzgertildi yamasa tolД±q ekran rejiminen shД±ЗµД±ldД±).",
        lockAdminNote: "Siz test qaЗµД±ydasД±n buzdiЕ„Д±z! OqД±tД±wshД± parolin kiritiЕ„:",
        lockPassPlaceholder: "OqД±tД±wshД± paroli",
        lockBtnUnlock: "AshД±w",
        lblUnblockPin: "Bloktan shД±ЗµarД±w paroli:",

        alertDuration: "IltД±mas, test waqtД±n durД±s kiritiЕ„!",
        teacherPinSaved: "SiziЕ„ pГЎniЕ„iz ushД±n sazlamalar tabД±slД± saqlandД±!",
        teacherTimerPrefix: "Sizge berilgen ruqsatnamaЕ„Д±z waqД±t juwmaqlanД±wД±na qaldД±:",
        teacherTimerMin: "minut",
        teacherTimerSecs: "sekund",
        adminLoginLink: "OqД±tД±wshД±lar hГЎm Admin kiriwi",
        backToStudentLogin: "OqД±wshД± aynasД±na qaytД±w",
        teacherPinSetterTitle: "PГЎniЕ„iz ushД±n PIN-kod hГЎm Test waqtД±n belgileЕ„",
        lblTeacherPin: "OqД±wshД±lar ushД±n PIN-kod:",
        lblTeacherDuration: "Test dawamiylД±ЗµД± (minut):",
        btnSaveTeacherSettings: "SazlamalardД± saqlaw",
        timeUpAlert: "SiziЕ„ waqtД±nshalД±q ruxsatnamaЕ„Д±z Гіz juwmaЗµД±na jetti!",
        alertDetails: "Д°ltimas, atД±Е„Д±z hГЎm klasД±Е„Д±zdД± tolД±q kiritiЕ„!",
        alertNoQuestions: "Sorawlar tabД±lmadД±!",
        alertFields: "BarlД±q orД±nlardД± toltД±rД±Е„!",
        alertAdded: "Soraw qosД±ldД±!",
        alertSelectFile: "Д°ltimas, dГЎslep Word (.docx) faylД±n saylaЕ„!",
        alertReadError: "FayldД± oqД±wda qГЎtelik jГєz berdi!",
        alertConfirmClear: "NГЎtiyjelerdi tolД±q Гіshirmekshisiz be?",
        alertNoExport: "Eksport qД±lД±w ushД±n natiyjeler tabД±lmadД±!",
        alertImportEmpty: "Fayl ishinen sГЎykes formattaЗµД± sorawlar tabД±lmadД±! Д°ltimas shablondД± tekseriЕ„.",
        alertConfirmDelete: "Bul sorawdД± Гіshirmekshisiz be?",
        alertTimeout: "WaqД±t tamamlandД±! Test avtomatik juwmaqlanadД±.",
        alertImportSuccess: "TabД±slД± juklendi:",
        alertImportSuccess2: "ta taza soraw qosД±ldД±!",
        btnDelete: "Г“shiriw",
        unknown: "Belgisiz",
        times: "mГЎrte",
        noResults: "HГЎzirshe natiyjeler tabД±lmadД±.",
        emptyLeaderboard: "Reyting kestesi bos.",
        notAnswered: "Juwap berilmegen",
        yourAnswer: "Siz saylaЗµan juwap:",
        noMistakes: "QutlД±qlaymД±z! Hesh qanday qГЎtege jol qoyД±lmadД±.",
        studentLabel: "OqД±wshД±:",
        percentageLabel: "Procent kГіretkishi:",
        timeSpent: "Sarp etilgen waqД±t:",
        violations: "QaЗµД±yda buzД±wshД±lД±qlar (Bloklar):",
        analysisLabel: "Analiz:",
        totalLimit: "UlД±wma limit:",
        min: "min",
        certTitle: "HГљRMET JARLГЌЗґГЌ",
        certGivenTo: "UsД± sertifikat tapsД±rД±ladД±:",
        studentOfClass: "-klass oqД±wshД±sД±",
        certText1: "PortalД±mД±zdaЗµД± imtixannan joqarД± natiyje",
        certText2: "arnawlД± pГЎnler boyД±nsha bekkem bilimin kГіrsetkeni ushД±n.",
        dateLabel: "SГЎne:",
        portalAdmin: "Mektep adminstraciyasД±",
        examResult: "Д°MTД°XAN NATД°YJESД°",
        analysisEx: "Гљlgi dГЎreje! Siz temanД± tolД±q Гіzlestirgensiz.",
        analysisGood: "JaqsД± natiyje. BilimiЕ„izdi jГЎne de bekkemlewiЕ„iz mГєmkin.",
        analysisSat: "QanaatlandararlД±q. TГЎkirarlaw kГіbirek talap etiledi.",
        analysisBad: "TГіmen natiyje. Д°ltimas, sabaqlД±qtД± qaytadan oqД±p shД±ЗµД±Е„.",
        lblFilterQuarter: "Sherek:",
        qAll: "BarlД±q sherekler",
        q1: "I sherek",
        q2: "II sherek",
        q3: "III sherek",
        q4: "IV sherek",
        analyticsTitle: "Sherek analizi (Kognitiv dГЎrejeler)",
        lblCognitive: "Kognitiv dГЎreje:",
        statTotalStudents: "OqД±wshД±lar sanД±",
        statAvgScore: "Ortasha kГіrsetkish (%)",
        statQuality: "Sapa kГіrsetkishi (70%+)",
        lblQFormat: "Soraw formatД±:",
        fmtClosed: "JabД±q test (A,B,C,D)",
        fmtOpen: "AshД±q soraw (Jazba)",
        lblOpenAnswer: "DurД±s juwap (Gilt sГіz):",
        phOpenAnswer: "JuwabД±Е„Д±zdД± kiritiЕ„...",
        lblWritten: "Jazba",
        comparisonTitle: "Eki sherekti Гіz-ara analiz qД±lД±w",
        btnCompare: "Analiz qД±lД±w",
        compIncreased: "Зµa Г“STД°",
        compDecreased: "Зµa PГЃSEYDГЌ",
        compSame: "Г“ZGERД°SSД°Z qaldД±",
        compConclusion: "PedagogikalД±q analiz:",
        compConclusionGood: "JaqsД± nГЎtiyje, qosД±msha sabaqlar Гіz paydasД±n bermekte.",
        compConclusionBad: "QГЎweterli jaЗµday, Гіzlestiriw tГіmenlegen. QosД±msha ilajlar kГіriw zГЎrГєr.",
        compConclusionNeutral: "Г“zlestiriw turaqlД±, biraq Гіsiw Гєstinde islew usД±nД±s etiledi.",
        subjectPlaceholder: "PГЎndi taЕ„laЕ„",
        subjOnaTili: "Ana tili",
        subjMatematika: "Matematika",
        subjFizika: "Fizika",
        subjKimyo: "Ximiya",
        subjBiologiya: "Biologiya",
        subjTarix: "Tariyx",
        subjHuquq: "HuqД±q",
        subjInformatika: "Informatika",
        settingsPinsTitle: "PГЎnler hГЎm PIN-kodlar",
        settingsPinsHint: "OqД±wshД±lar testti baslawД± ushД±n hГЎr bir pГЎnge arnawlД± PIN-kod ornatД±Е„.",
        settingsGeminiTitle: "Gemini AI sazlamalarД±",
        settingsGeminiHint: "Pedagogik analiz Гіtkeriw ushД±n Google Gemini API giltin kiritiЕ„.",
        lblGeminiKey: "Gemini AI API Gilti:",
        btnAnalyzeAI: "Gemini AI analizвњЁ",
        aiAnalyzing: "Gemini AI klass nГЎtiyjelerin hГЎm kognitivlik dГЎrejelerin analiz etpekte...",
        btnCloseAI: "NГЎtiyjeni jabД±w",
        lblTargetClass: "MГіljellengen sД±nД±p:",
        alertNoClassTest: "Bul sД±nД±p ushД±n test tabilmadД±!",
        lblSelectStudent: "OquwshД±nД± saylaЕ„:",
        selStudent: "OquwshД±nД± saylaЕ„...",
        btnViewDetails: "TolД±q kГіriw",
        btnCloseDetails: "JabД±w",
        lblCorrectAnswer: "DurД±s juwap",
        lblStudentAnswer: "OquwshД±nД±Е„ juwabД±",
        aiAnalysisTitle: "Gemini AI Analizi",
        thSubject: "PГЎn",
        alertWrongPin: "QГЎte! Bul pГЎn ushД±n PIN-kod qГЎte kiritildi.",
        alertGeminiNoKey: "QГЎte! Iltimas, Sazlamalar bГіliminen Gemini API giltin kiritiЕ„.",
        geminiLoading: "Gemini AI analiz qД±lmaqta, iltimas kГєtiЕ„...",
        lblTestType: "Test tГєri:",
        testTypeBSB: "BSB (Bap boyД±nsha bahalaw)",
        testTypeCHSB: "ShSB (Shereklik boyД±nsha bahalaw)",
        lblUploadImage: "SГєwret jГєklew (IqtД±yariy)",
        instructionRules: "Test qaЗµД±ydalarД±:",
        rule1: "Testti baslaЗµannan soЕ„ waqД±t artqa esaplanД±wД± baslanadД±.",
        rule2: "Betti jaЕ„alaw (Refresh) yamasa jabД±w qadaЗµan etiledi.",
        rule3: "JabД±q testlerde tek bir durД±s juwaptД± belgileЕ„, ashД±q sawallarda bolsa juwaptД± klaviaturada qolda jazД±Е„.",
        btnBeginTest: "Testti baslaw",
        lblTime: "Test dawamiylД±ЗµД±:",
        lblCount: "Sorawlar sanД±:",
        adminLogout: "ShД±ЗµД±w",
        tabQR: "QR Kod",
        addQTitle: "Qoldan soraw qosД±w",
        lblCorrectAns: "DurД±s:",
        btnAddQuestion: "SorawdД± qosД±w",
        wordUploaderTitle: "Word (Docx) juklew",
        wordUploaderInfo: "Fayl tГіmendegi qatД±y formatda bolД±wД± kerek:",
        btnUploadWord: "BazaЗµa qosД±w",
        dbQuestionsTitle: "Bazada:",
        dbQuestionsCount: "ta soraw",
        teacherTokensTitle: "OqД±tД±wshД±lar ushД±n waqtД±nshalД±q ruqsatnamalar",
        teacherTokensHint: "OqД±tД±wshД±larЗµa tek Гіz pГЎnin basqarД±w huquqД±n beretuЗµД±n waqtД±nshalД±q paroller (tokenler) jaratД±Е„.",
        lblDefaultTime: "Standart test dawamiylД±ЗµД± (minut):",
        settingsTgHint: "OqД±wshД± testti juwmaqlaЗµannan keyin, nГЎtiyje avtomatik Telegram arqalД± jiberiledi.",
        lblTgToken: "Bot Token:",
        lblTgChatId: "Chat ID (yaki Gruppa ID):",
        secAnswersTitle: "Test juwaplarД± (OqД±wshД±Зµa)",
        secAnswersLabel: "Test yakunida to'g'ri javoblarni o'quvchiga ko'rsatish:",
    btnShowAnswersOn: "Juwaplardı kórsetiw: QOSILǴAN",
    btnShowAnswersOff: "Juwaplardı kórsetiw: ÓCHIRILǴAN",
    btnShowAnswersOn: "Javoblarni ko'rsatish: YOQILGAN",
    btnShowAnswersOff: "Javoblarni ko'rsatish: O'CHIRILGAN",
        secAnswersHint: "QГЎwipsizlik kГіzqarasД±nan durД±s juwaplar jasД±rД±lЗµan.",
        qrCodeTitle: "Platforma ushД±n QR Kod",
        qrCodeHint: "UsД± QR kod arqalД± oqД±wshД±lar testke tez kiriwi mГєmkin.",
        btnDownloadQR: "QR KodtД± juklep alД±w (PNG)",
        phQuestionText: "Soraw tekstin usД± jerge jazД±Е„...",
        phOptA: "A variant...",
        phOptB: "B variant...",
        phOptC: "C variant...",
        phOptD: "D variant...",
        lblAdminQuarter: "Sherek:",
        settingsSavedMsg: "BarlД±q sazlamalar saqlandД±!",
        alertFillFields: "BarlД±q orД±nlardД± toltД±rД±Е„!",
        confirmDeleteQ: "Bul sorawdД± Гіshirmekshisiz be?",
        confirmClearResults: "NГЎtiyjelerdi tolД±q Гіshirmekshisiz be?",
        msgResultsCleared: "NГЎtiyjeler tazalandД±!",
        msgQuestionDeleted: "Soraw Гіshirildi!",
        btnFinishQuiz: "Juwmaqlaw",
        thPercentage: "Procent",
        thDate: "SГЎne",
        alertGeminiKey: "Gemini API gilti sazlanbaan! Sazlamalar bГіliminen kiritiЕ„.",
        tempPasswordExpired: "Waqıtshalıq parol múddeti bitken!",
        thExpireDate: "Amal etiw múddeti:",
        currentActiveToken: "Házirgi waqıtshalıq parol:",
        noActiveToken: "Aktiv waqıtshalıq parol joq"
    },
    en: {
        toastWarning: "Viewing code is prohibited due to system security!",
        schoolName: "Khodjeyli specialized school",
        welcomeMsg: "Welcome! Enter your details to start the test.",
        namePlaceholder: "Full Name",
        classPlaceholder: "Class / Group (e.g., 9-A, 11-B)",
        pinPlaceholder: "Enter specific PIN code",
        cogKnowing: "Knowing / Knowledge",
        cogApp: "Application",
        cogReasoning: "Reasoning",
        selClass: "Select Class",
        selQuarter: "Select Quarter",
        btnExportExcel: "Download as Excel (SA/TSA)",
        startBtn: "Login",
        adminLoginBtn: "Enter Admin Panel",
        leaderboardTitle: "рџЏ† Top-10 Leaderboard",
        thRank: "Rank",
        thName: "Name",
        thClass: "Class",
        thPoints: "Points",
        thTime: "Time",
        adminModalTitle: "Admin System Login",
        adminPassPlaceholder: "Enter Admin Password",
        adminModalSubmit: "Login",
        adminModalCancel: "Cancel",
        incorrectPass: "Incorrect password!",
        adminPanelTitle: "Admin Control Panel",
        adminLogoutBtn: "Close Panel",
        tabQuestions: "Questions Management",
        tabResults: "Student Results",
        tabSettings: "Settings",
        tabQr: "Get QR Code",
        tabSecurity: "Security",
        secTitle: "Security Settings",
        secShowAnswersTitle: "Show answers in results",
        secShowAnswersDesc: "Will the student be able to see the list of correct answers to the questions they got wrong at the end of the test?",
        hiddenAnswersMsg: "Correct answers are hidden for security reasons.",
        settingsTeachersTitle: "Temporary permissions for teachers",
        settingsTeachersHint: "Generate a temporary password (token) so teachers can add questions and view results for their subject.",
        lblTeacherName: "Teacher Full Name:",
        lblTeacherSubject: "Select Subject:",
        lblTeacherExpire: "Expiration time:",
        exp2h: "2 hours",
        exp1d: "1 day",
        exp1w: "1 week",
        exp1m: "1 month",
        btnGenerateToken: "Generate Password",
        thTeacherName: "Full Name",
        thTeacherSubject: "Subject",
        thTeacherToken: "Token",
        thTeacherExpire: "Expires At",
        thTeacherAction: "Action",
        alertTokenExpired: "This password has expired!",
        manualAddTitle: "Add New Question (Manual)",
        qTextPlaceholder: "Question text",
        optAPlaceholder: "Option A",
        optBPlaceholder: "Option B",
        optCPlaceholder: "Option C",
        optDPlaceholder: "Option D",
        lblCorrect: "Correct answer:",
        optA: "Option A",
        optB: "Option B",
        optC: "Option C",
        optD: "Option D",
        lblPoints: "Question points:",
        saveQBtn: "Save Question",
        wordImportTitle: "Upload from Word (.docx)",
        wordImportHint: "Your Word file must match the following template:",
        btnImport: "Import Questions",
        questionsListTitle: "Available Questions",
        resultsTableTitle: "Results Table",
        lblFilterClass: "Filter by Class:",
        filterAll: "All",
        btnExportCsv: "Export as Excel (CSV)",
        btnClearResults: "Clear All Results",
        thScore: "Score",
        thPercent: "Percentage",
        thBlocks: "Blocks",
        settingsGeneralTitle: "General Test Settings",
        lblTestDuration: "Test Duration (minutes):",
        settingsTelegramTitle: "Settings",
        settingsTelegramHint: "After each student finishes the test, their results will be sent to you via Telegram.",
        lblTgBotToken: "Telegram Bot Token:",
        lblTgChatId: "Telegram Chat ID (Group or Personal ID):",
        btnSaveSettings: "Save All Settings",
        qrTitle: "Project QR Code",
        qrHint: "Students can quickly access the test using this QR code.",
        downloadQr: "Download QR Code (PNG)",
        quizInfoQuestion: "Question",
        quizInfoPoints: "points",
        nextBtn: "Next Question",
        testFinishedTitle: "Test Finished",
        certCongrats: "Congratulations! You achieved a high score.",
        certInfo: "You can download your certificate.",
        btnDownloadCert: "Download Certificate (PNG)",
        errorReviewTitle: "Review Mistakes",
        btnBackToHome: "Back to Home",
        lockWarningTitle: "YOU ARE BLOCKED!",
        lockWarningText: "System usage rules violated (screen changed or exited full screen mode).",
        lockAdminNote: "You violated the test rules! Enter the teacher's password to continue:",
        lockPassPlaceholder: "Teacher password",
        lockBtnUnlock: "Unlock",
        lblUnblockPin: "Unblock PIN:",
        
        alertDuration: "Please enter a valid test duration!",
        teacherPinSaved: "Settings for your subject have been saved successfully!",
        teacherTimerPrefix: "Your temporary permission expires in:",
        teacherTimerMins: "minutes",
        teacherTimerSecs: "seconds",
        adminLoginLink: "Teacher and Admin Login",
        backToStudentLogin: "Back to Student Screen",
        teacherPinSetterTitle: "Set PIN Code and Test Time for your subject",
        lblTeacherPin: "PIN Code for students:",
        lblTeacherDuration: "Test duration (minutes):",
        btnSaveTeacherSettings: "Save Settings",
        timeUpAlert: "Your temporary permission has expired!",
        alertDetails: "Please enter your full name and class!",
        alertNoQuestions: "No questions available! Please contact the admin.",
        alertFields: "Fill in all fields!",
        alertAdded: "Question added!",
        alertSelectFile: "Please select a Word (.docx) file first!",
        alertReadError: "Error reading the file!",
        alertConfirmClear: "Are you sure you want to completely clear all results?",
        alertNoExport: "No results available to export!",
        alertImportEmpty: "No questions matching the format were found in the file! Please check the template.",
        alertConfirmDelete: "Are you sure you want to delete this question?",
        alertTimeout: "Time's up! The test will automatically finish.",
        alertImportSuccess: "Successfully loaded:",
        alertImportSuccess2: "new questions added!",
        btnDelete: "Delete",
        unknown: "Unknown",
        times: "times",
        noResults: "No results available yet.",
        emptyLeaderboard: "Leaderboard is empty.",
        notAnswered: "Not answered",
        yourAnswer: "Your answer:",
        noMistakes: "Congratulations! No mistakes were made.",
        studentLabel: "Student:",
        percentageLabel: "Percentage:",
        timeSpent: "Time spent:",
        violations: "Violations (Blocks):",
        analysisLabel: "Analysis:",
        totalLimit: "Total limit:",
        min: "min",
        certTitle: "CERTIFICATE OF ACHIEVEMENT",
        certGivenTo: "This certificate is awarded to:",
        studentOfClass: "student of class",
        certText1: "For achieving a high score",
        certText2: "in the examination and demonstrating strong knowledge.",
        dateLabel: "Date:",
        portalAdmin: "Portal Administration",
        examResult: "EXAM RESULT",
        analysisEx: "Excellent! You have mastered the subject perfectly.",
        analysisGood: "Good result. You can further consolidate your knowledge.",
        analysisSat: "Satisfactory. More revision is required.",
        analysisBad: "Low result. Please review the textbook again.",
        lblFilterQuarter: "Quarter:",
        qAll: "All quarters",
        q1: "I quarter",
        q2: "II quarter",
        q3: "III quarter",
        q4: "IV quarter",
        analyticsTitle: "Quarterly Analytics (Cognitive Levels)",
        lblCognitive: "Cognitive level:",
        statTotalStudents: "Total Students",
        statAvgScore: "Average Score (%)",
        statQuality: "Quality Indicator (70%+)",
        lblQFormat: "Question format:",
        fmtClosed: "Closed test (A,B,C,D)",
        fmtOpen: "Open question (Written)",
        lblOpenAnswer: "Correct answer text (Keyword):",
        phOpenAnswer: "Enter your answer...",
        lblWritten: "Written",
        comparisonTitle: "Compare Two Quarters",
        btnCompare: "Analyze",
        compIncreased: "INCREASED by",
        compDecreased: "DECREASED by",
        compSame: "remained UNCHANGED",
        compConclusion: "Pedagogical Conclusion:",
        compConclusionGood: "Good result, additional lessons are showing positive effects.",
        compConclusionBad: "Concerning situation, individual work with students is required.",
        compConclusionNeutral: "No change, efforts need to be increased.",
        subjectPlaceholder: "Select Subject",
        pinPlaceholder: "Enter specific PIN code",
        subjOnaTili: "Native Language",
        subjMatematika: "Mathematics",
        subjFizika: "Physics",
        subjKimyo: "Chemistry",
        subjBiologiya: "Biology",
        subjTarix: "History",
        subjHuquq: "Law",
        subjInformatika: "Informatics",
        settingsPinsTitle: "Subjects and PIN Codes",
        settingsPinsHint: "Set a specific PIN code for each subject to allow students to start the test.",
        settingsGeminiTitle: "Gemini AI Settings",
        settingsGeminiHint: "Enter your Google Gemini API key to run pedagogical analysis.",
        lblGeminiKey: "Gemini AI API Key:",
        btnAnalyzeAI: "Gemini AI Analysis вњЁ",
        aiAnalyzing: "Gemini AI is analyzing class results and cognitive levels...",
        btnCloseAI: "Close Result",
        lblTargetClass: "Target Class:",
        alertNoClassTest: "No test found for this class!",
        lblSelectStudent: "Select Student:",
        selStudent: "Select Student...",
        btnViewDetails: "View Details",
        btnCloseDetails: "Close",
        lblCorrectAnswer: "Correct Answer",
        lblStudentAnswer: "Student's Answer",
        aiAnalysisTitle: "Gemini AI Analysis",
        thSubject: "Subject",
        alertWrongPin: "Error! Incorrect PIN code for this subject.",
        alertGeminiNoKey: "Error! Please enter the Gemini API key in the Settings section.",
        geminiLoading: "Gemini AI is analyzing, please wait...",
        lblTestType: "Test Type:",
        testTypeBSB: "SA (Summative Assessment)",
        testTypeCHSB: "TSA (Term Summative Assessment)",
        lblUploadImage: "Upload Image",
        instructionRules: "Test Rules:",
        rule1: "The timer will start counting down once you begin the test.",
        rule2: "Refreshing or closing the page is prohibited (results may be lost).",
        rule3: "For multiple-choice questions, select only one correct answer. For open questions, type your answer using the keyboard.",
        btnBeginTest: "Start Test",
        lblTime: "Time:",
        lblCount: "Question count:",
        adminLogout: "Logout",
        tabQR: "QR Code",
        addQTitle: "Add Question Manually",
        lblCorrectAns: "Correct:",
        btnAddQuestion: "Add Question",
        wordUploaderTitle: "Upload Word (Docx)",
        wordUploaderInfo: "The file must follow this strict format:",
        btnUploadWord: "Add to Database",
        dbQuestionsTitle: "In database:",
        dbQuestionsCount: "questions",
        teacherTokensTitle: "Temporary teacher permissions",
        teacherTokensHint: "Generate temporary passwords (tokens) so teachers can manage only their subject.",
        lblDefaultTime: "Default test duration (minutes):",
        settingsTgHint: "When a student finishes a test, the result is sent to your Telegram bot or group.",
        lblTgToken: "Bot Token:",
        lblTgChatId: "Chat ID (or Group ID):",
        secAnswersTitle: "Test Answers (For Students)",
        secAnswersLabel: "Test yakunida to'g'ri javoblarni o'quvchiga ko'rsatish:",
    btnShowAnswersOn: "Javoblarni ko'rsatish: YOQILGAN",
    btnShowAnswersOff: "Javoblarni ko'rsatish: O'CHIRILGAN",
        secAnswersHint: "Correct answers are hidden for security reasons.",
        qrCodeTitle: "Platform QR Code",
        qrCodeHint: "Students can quickly access the test using this QR code.",
        btnDownloadQR: "Download QR Code (PNG)",
        phQuestionText: "Enter question text here...",
        phOptA: "Option A...",
        phOptB: "Option B...",
        phOptC: "Option C...",
        phOptD: "Option D...",
        lblAdminQuarter: "Quarter:",
        settingsSavedMsg: "All settings saved!",
        alertFillFields: "Please fill in all fields!",
        confirmDeleteQ: "Delete this question?",
        confirmClearResults: "Clear all results?",
        msgResultsCleared: "Results cleared!",
        msgQuestionDeleted: "Question deleted!",
        btnFinishQuiz: "Finish",
        thPercentage: "Percentage",
        thDate: "Date",
        alertGeminiKey: "Gemini API key is not configured! Enter it in Settings.",
        tempPasswordExpired: "Temporary password has expired!",
        thExpireDate: "Expiration date:",
        currentActiveToken: "Current temporary password:",
        noActiveToken: "No active temporary password"
    }
};

let currentLang = localStorage.getItem('quiz_lang') || 'uz';

function t(key) {
    return translations[currentLang][key] || key;
}

function applyTranslations() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[currentLang] && translations[currentLang][key]) {
            el.innerHTML = translations[currentLang][key];
        }
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (translations[currentLang] && translations[currentLang][key]) {
            el.setAttribute('placeholder', translations[currentLang][key]);
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    applyTranslations();

    const langBtns = document.querySelectorAll('.lang-btn');
    langBtns.forEach(btn => {
        if (btn.getAttribute('data-lang') === currentLang) {
            btn.classList.add('active');
        } else {
            btn.classList.remove('active');
        }

        btn.addEventListener('click', (e) => {
            langBtns.forEach(b => b.classList.remove('active'));
            e.target.classList.add('active');
            currentLang = e.target.getAttribute('data-lang');
            localStorage.setItem('quiz_lang', currentLang);
            applyTranslations();
            
            // Re-render components if methods are available in global scope
            if (typeof renderLeaderboard === 'function' && !document.getElementById('auth-screen').classList.contains('hidden')) {
                renderLeaderboard();
            }
            if (typeof renderQuestionsList === 'function' && !document.getElementById('admin-panel').classList.contains('hidden')) {
                renderQuestionsList();
                if (typeof renderResultsTable === 'function') {
                    renderResultsTable();
                }
            }
        });
    });
});


