const translations = {
    uz: {
        toastWarning: "Tizim xavfsizligi tufayli kodni ko'rish taqiqlanadi!",
        schoolName: "Xo'jayli tumani ixtisoslashtirilgan maktabi",
        welcomeMsg: "Xush kelibsiz! Testga kirish uchun ma'lumotlarni kiriting.",
        namePlaceholder: "F.I.SH.",
        classPlaceholder: "Sinf (Masalan: 9-A, 11-B)",
        pinPlaceholder: "Maxsus kod (PIN)",
        cogKnowing: "Bilish",
        cogApp: "Qo'llash",
        cogReasoning: "Mulohaza qilish",
        selClass: "Sinfni tanlang",
        selQuarter: "Chorakni tanlang",
        btnExportExcel: "Excel formatda yuklash (BSB/CHSB)",
        startBtn: "Kirish",
        adminLoginBtn: "Admin paneliga kirish",
        leaderboardTitle: "🏆 Top-10 Reyting ⭐",
        thRank: "O'rin",
        thName: "F.I.SH.",
        thClass: "Sinf",
        thPoints: "Ball",
        thTime: "Vaqt",
        adminModalTitle: "Admin tizimiga kirish",
        adminPassPlaceholder: "Admin parolini kiriting",
        adminModalSubmit: "Kirish",
        adminModalCancel: "Bekor qilish",
        incorrectPass: "Noto'g'ri parol!",
        adminPanelTitle: "Admin boshqaruv paneli",
        adminLogoutBtn: "Panelni yopish",
        tabQuestions: "Savollar boshqaruvi",
        tabResults: "O'quvchilar natijalari",
        tabSettings: "Sozlamalar",
        tabQr: "QR-kod olish",
        tabSecurity: "Xavfsizlik",
        secTitle: "Xavfsizlik Sozlamalari",
        secShowAnswersTitle: "Natijalarda javoblarni ko'rsatish",
        secShowAnswersDesc: "Test yakunida o'quvchi xato qilgan savollarning to'g'ri javoblari ro'yxatini ko'ra oladimi?",
        hiddenAnswersMsg: "Xavfsizlik nuqtai nazaridan to'g'ri javoblar yashirilgan.",
        settingsTeachersTitle: "O'qituvchilar uchun vaqtinchalik ruxsatnomalar",
        settingsTeachersHint: "O'qituvchilar o'z faniga savol qo'shishi va natijalarni ko'rishi uchun vaqtinchalik parol (token) yarating.",
        lblTeacherName: "O'qituvchi F.I.SH:",
        lblTeacherSubject: "Fanni tanlang:",
        lblTeacherExpire: "Amal qilish muddati:",
        exp2h: "2 soat",
        exp1d: "1 kun",
        exp1w: "1 hafta",
        exp1m: "1 oy",
        btnGenerateToken: "Parol yaratish",
        thTeacherName: "F.I.SH.",
        thTeacherSubject: "Fan",
        thTeacherToken: "Parol",
        thTeacherExpire: "Tugash vaqti",
        thTeacherAction: "Amal",
        alertTokenExpired: "Ushbu parolning amal qilish muddati tugagan!",
        manualAddTitle: "Yangi savol qo'shish (Qo'lda)",
        qTextPlaceholder: "Savol matni",
        optAPlaceholder: "Variant A",
        optBPlaceholder: "Variant B",
        optCPlaceholder: "Variant C",
        optDPlaceholder: "Variant D",
        lblCorrect: "To'g'ri javob:",
        optA: "Variant A",
        optB: "Variant B",
        optC: "Variant C",
        optD: "Variant D",
        lblPoints: "Savol balli:",
        saveQBtn: "Savolni saqlash",
        wordImportTitle: "Word fayldan yuklash (.docx)",
        wordImportHint: "Word faylingiz quyidagi shablonga mos bo'lishi kerak:",
        btnImport: "Savollarni import qilish",
        questionsListTitle: "Mavjud savollar",
        resultsTableTitle: "Natijalar jadvali",
        lblFilterClass: "Sinf bo'yicha filter:",
        filterAll: "Barchasi",
        btnExportCsv: "Excel formatda yuklab olish (CSV)",
        btnClearResults: "Barcha natijalarni tozalash",
        thScore: "To'plangan ball",
        thPercent: "Foiz",
        thBlocks: "Bloklar soni",
        settingsGeneralTitle: "Test umumiy sozlamalari",
        lblTestDuration: "Test vaqti (daqiqada):",
        settingsTelegramTitle: "Sozlamalar",
        settingsTelegramHint: "Har bir o'quvchi testni tugatgandan so'ng, uning natijalari Telegram orqali sizga yuboriladi.",
        lblTgBotToken: "Telegram Bot Token:",
        lblTgChatId: "Telegram Chat ID (Guruh yoki shaxsiy ID):",
        btnSaveSettings: "Barcha sozlamalarni saqlash",
        qrTitle: "Loyiha QR-kodi",
        qrHint: "Ushbu QR-kod yordamida o'quvchilar testga tezkor kirishlari mumkin.",
        downloadQr: "QR-kodni yuklab olish (PNG)",
        quizInfoQuestion: "Savol",
        quizInfoPoints: "ball",
        nextBtn: "Keyingi savol",
        testFinishedTitle: "Test Yakunlandi",
        certCongrats: "Tabriklaymiz! Siz yuqori natija ko'rsatdingiz.",
        certInfo: "Siz o'z sertifikatingizni yuklab olishingiz mumkin.",
        btnDownloadCert: "Sertifikatni yuklab olish (PNG)",
        errorReviewTitle: "Xatolar ustida ishlash",
        btnBackToHome: "Asosiy sahifaga qaytish",
        lockWarningTitle: "SIZ BLOKLANDINGIZ!",
        lockWarningText: "Tizimdan foydalanish qoidalari buzildi (ekran o'zgartirildi yoki to'liq ekran rejimidan chiqildi).",
        lockAdminNote: "Siz test qoidalarini buzgansiz! Testni davom ettirish uchun o'qituvchi parolini kiriting:",
        lockPassPlaceholder: "O'qituvchi paroli",
        lockBtnUnlock: "Ochish",
        lblUnblockPin: "Blokdan chiqarish paroli:",
        
        // JS specific
        alertDuration: "Iltimos, test vaqtini to'g'ri kiriting!",
        teacherPinSaved: "Faningiz uchun sozlamalar muvaffaqiyatli saqlandi!",
        teacherTimerPrefix: "Sizning ruxsatnomangiz tugashiga qoldi:",
        teacherTimerMins: "daqiqa",
        teacherTimerSecs: "soniya",
        adminLoginLink: "O'qituvchilar va Admin kirishi",
        backToStudentLogin: "O'quvchi oynasiga qaytish",
        teacherPinSetterTitle: "Faningiz uchun PIN-kod va Test vaqtini belgilang",
        lblTeacherPin: "O'quvchilar uchun PIN-kod:",
        lblTeacherDuration: "Test davomiyligi (daqiqa):",
        btnSaveTeacherSettings: "Sozlamalarni saqlash",
        timeUpAlert: "Sizning vaqtinchalik ruxsatnomangiz o'z nihoyasiga yetdi!",
        alertDetails: "Iltimos, ismingiz va sinfingizni to'liq kiriting!",
        alertNoQuestions: "Savollar mavjud emas! Iltimos, admin bilan bog'laning.",
        alertFields: "Barcha maydonlarni to'ldiring!",
        alertAdded: "Savol qo'shildi!",
        alertSelectFile: "Iltimos, avval Word (.docx) faylini tanlang!",
        alertReadError: "Faylni o'qishda xatolik yuz berdi!",
        alertConfirmClear: "Natijalarni butunlay o'chirmoqchimisiz?",
        alertNoExport: "Eksport qilish uchun natijalar mavjud emas!",
        alertImportEmpty: "Fayl ichidan mos formatdagi savollar topilmadi! Iltimos shablonni tekshiring.",
        alertConfirmDelete: "Ushbu savolni o'chirib tashlamoqchimisiz?",
        alertTimeout: "Vaqt tugadi! Test avtomatik yakunlanadi.",
        alertImportSuccess: "Muvaffaqiyatli yuklandi:",
        alertImportSuccess2: "ta yangi savol qo'shildi!",
        btnDelete: "O'chirish",
        unknown: "Noma'lum",
        times: "marta",
        noResults: "Hozircha natijalar mavjud emas.",
        emptyLeaderboard: "Reyting jadvali bo'sh.",
        notAnswered: "Javob berilmagan",
        yourAnswer: "Siz tanlagan javob:",
        noMistakes: "Tabriklaymiz! Hech qanday xatoga yo'l qo'yilmadi.",
        studentLabel: "Talaba:",
        percentageLabel: "Foiz ko'rsatkichi:",
        timeSpent: "Sarflangan vaqt:",
        violations: "Qoidabuzarliklar (Bloklar):",
        analysisLabel: "Tahlil:",
        totalLimit: "Jami limit:",
        min: "daq",
        certTitle: "SERTIFIKAT",
        certGivenTo: "Ushbu sertifikat topshiriladi:",
        studentOfClass: "-sinf o'quvchisi",
        certText1: "Portalimizdagi imtihondan yuqori natija",
        certText2: "maxsus fanlar bo'yicha mustahkam bilimini namoyon etganligi uchun.",
        dateLabel: "Sana:",
        portalAdmin: "Portal Ma'muriyati",
        examResult: "IMTIHON NATIJASI",
        analysisEx: "A'lo daraja! Siz mavzuni mukammal o'zlashtirgansiz.",
        analysisGood: "Yaxshi natija. Bilimingizni yanada mustahkamlashingiz mumkin.",
        analysisSat: "Qoniqarli. Takrorlash ko'proq talab etiladi.",
        analysisBad: "Past natija. Iltimos, darslikni qaytadan o'qib chiqing.",
        lblFilterQuarter: "Chorak:",
        qAll: "Barcha choraklar",
        q1: "I chorak",
        q2: "II chorak",
        q3: "III chorak",
        q4: "IV chorak",
        analyticsTitle: "Choraklik Tahlil (Kognitiv darajalar)",
        lblCognitive: "Kognitiv daraja:",
        statTotalStudents: "O'quvchilar soni",
        statAvgScore: "O'rtacha ko'rsatkich (%)",
        statQuality: "Sifat ko'rsatkichi (70%+)",
        lblQFormat: "Savol formati:",
        fmtClosed: "Yopiq test (A,B,C,D)",
        fmtOpen: "Ochiq savol (Yozma)",
        lblOpenAnswer: "To'g'ri javob matni (Kalit so'z):",
        phOpenAnswer: "Javobingizni kiriting...",
        lblWritten: "Yozma",
        comparisonTitle: "Ikki chorakni o'zaro tahlil qilish",
        btnCompare: "Tahlil qilish",
        compIncreased: "ga O'SDI",
        compDecreased: "ga PASAYDI",
        compSame: "O'ZGARISHSZ qoldi",
        compConclusion: "Pedagogik tahlil:",
        compConclusionGood: "Yaxshi natija, qo'shimcha darslar o'z samarasini bermoqda.",
        compConclusionBad: "Xavotirli holat, o'zlashtirish tushib ketgan. Qo'shimcha chora-tadbirlar ko'rish zarur.",
        compConclusionNeutral: "O'zlashtirish barqaror, ammo o'sish ustida ishlash tavsiya etiladi",
        subjectPlaceholder: "Fanni tanlang",
                subjOzbek: "O'zbek tili",
        subjSanat: "San'at",
        subjRus: "Rus tili",
        subjIngliz: "Ingliz tili",
        subjTabiiy: "Tabiiy fan",
        subjOzbTarix: "O'zbekiston tarixi",
        subjJahonTarix: "Jahon tarixi",
        subjQorTarix: "Qoraqalpog'iston tarixi",
        subjAdabiyot: "Adabiyot",
        subjGeografiya: "Geografiya",
        subjTexnologiya: "Texnologiya",
        subjAlgebra: "Algebra",
        subjGeometriya: "Geometriya",
        settingsPinsTitle: "Fanlar va PIN-kodlar",
        settingsPinsHint: "O'quvchilar testni boshlashi uchun har bir fanga maxsus PIN-kod o'rnating.",
        settingsGeminiTitle: "Gemini AI Sozlamalari",
        settingsGeminiHint: "Pedagogik tahlil o'tkazish uchun Google Gemini API kalitini kiriting.",
        lblGeminiKey: "Gemini AI API Kaliti:",
        btnAnalyzeAI: "Gemini AI tahlili",
        aiAnalyzing: "Gemini AI sinf natijalari va kognitiv darajalarni tahlil qilmoqda...",
        btnCloseAI: "Natijani yopish",
        lblTargetClass: "Sinfni tanlash:",
        alertNoClassTest: "Ushbu sinf uchun test topilmadi!",
        lblSelectStudent: "O'quvchini tanlang:",
        selStudent: "O'quvchini tanlang...",
        btnViewDetails: "Batafsil ko'rish",
        btnCloseDetails: "Yopish",
        lblCorrectAnswer: "To'g'ri javob",
        lblStudentAnswer: "O'quvchi javobi",
        aiAnalysisTitle: "Gemini AI Tahlili",
        thSubject: "Fan",
        alertWrongPin: "Xato! Bu fan uchun PIN-kod noto'g'ri kiritildi.",
        alertGeminiNoKey: "Xato! Iltimos, Sozlamalar bo'limidan Gemini API kalitini kiriting.",
        geminiLoading: "Gemini AI tahlil qilmoqda, iltimos kuting...",
        lblTestType: "Test turi:",
        testTypeBSB: "BSB",
        testTypeCHSB: "CHSB",
        lblUploadImage: "Rasm yuklash",
        instructionRules: "Test ishlash qoidalari:",
        rule1: "Testni boshlagandan so'ng vaqt ortga hisoblana boshlaydi.",
        rule2: "Sahifani yangilash (Refresh) yoki yopish taqiqlanadi (natija yo'qolishi mumkin).",
        rule3: "Yopiq testlarda faqat bitta to'g'ri javobni belgilang, ochiq savollarda esa javobni klaviaturada qo'lda yozing.",
        btnBeginTest: "Testni boshlash",
        lblTime: "Vaqt:",
        lblCount: "Savollar soni:",
        adminLogout: "Chiqish",
        tabQR: "QR Kod",
        addQTitle: "Qo'lda Savol Qo'shish",
        lblCorrectAns: "To'g'ri:",
        btnAddQuestion: "Savolni Qo'shish",
        wordUploaderTitle: "Word (Docx) yuklash",
        wordUploaderInfo: "Fayl quyidagi qat'iy formatda bo'lishi shart:",
        btnUploadWord: "Bazaga qo'shish",
        dbQuestionsTitle: "Bazada:",
        dbQuestionsCount: "ta savol",
        teacherTokensTitle: "O'qituvchilar uchun vaqtinchalik ruxsatnomalar",
        teacherTokensHint: "O'qituvchilarga faqat o'z fanini boshqarish huquqini beruvchi vaqtinchalik parollar (tokenlar) yarating.",
        lblDefaultTime: "Standart Test davomiyligi (daqiqa):",
        settingsTgHint: "O'quvchi testni yakunlaganda, natija avtomatik ravishda telegram bot yoki guruhga yuboriladi.",
        lblTgToken: "Bot Token:",
        lblTgChatId: "Chat ID (yoki Guruh ID):",
        secAnswersTitle: "Test Javoblari (O'quvchiga)",
        secAnswersLabel: "Test yakunida to'g'ri javoblarni o'quvchiga ko'rsatish:",
    btnShowAnswersOn: "Javoblarni ko'rsatish: YOQILGAN",
    btnShowAnswersOff: "Javoblarni ko'rsatish: O'CHIRILGAN",
        secAnswersHint: "Xavfsizlik nuqtai nazaridan to'g'ri javoblar yashirilgan.",
        qrCodeTitle: "Platforma uchun QR Kod",
        qrCodeHint: "Ushbu QR kod orqali o'quvchilar testga tez va oson kirishlari mumkin.",
        btnDownloadQR: "QR Kodni Yuklab Olish (PNG)",
        phQuestionText: "Savol matnini bu yerga yozing...",
        phOptA: "A varianti...",
        phOptB: "B varianti...",
        phOptC: "C varianti...",
        phOptD: "D varianti...",
        lblAdminQuarter: "Chorak:",
        settingsSavedMsg: "Barcha sozlamalar saqlandi!",
        alertFillFields: "Barcha maydonlarni to'ldiring!",
        confirmDeleteQ: "Ushbu savolni o'chirmoqchimisiz?",
        confirmClearResults: "Natijalarni butunlay o'chirmoqchimisiz?",
        msgResultsCleared: "Natijalar tozalandi!",
        msgQuestionDeleted: "Savol o'chirildi!",
        btnFinishQuiz: "Yakunlash",
        thPercentage: "Foiz",
        thDate: "Sana",
        alertGeminiKey: "Gemini API kaliti sozlanmagan! Sozlamalar bo'limidan kiriting.",
        tempPasswordExpired: "Vaqtinchalik parol muddati tugagan!",
        thExpireDate: "Amal qilish muddati:",
        currentActiveToken: "Joriy vaqtinchalik parol:",
        noActiveToken: "Faol vaqtinchalik parol mavjud emas"
      },
      qq: {
        toastWarning: "Sistema qawipsizligi sebepli kodtı kіriw qadaǵalanadı!",
        schoolName: "Xojeli rayonı qánigelestirilgen mektebi",
        welcomeMsg: "Xosh keldińiz! Testke kiriw ushın maǵlıwmatlardı kiritiń.",
        namePlaceholder: "Oqıwshınıń F.A.Áa.",
        classPlaceholder: "Klass (Máselen: 9-A, 11-B)",
        pinPlaceholder: "PIN-kodtı kiritiń",
        cogKnowing: "Biliw",
        cogApp: "Qollaw",
        cogReasoning: "Pikirlew",
        selClass: "Klastı tańlań",
        selQuarter: "Sherekti tańlań",
        btnExportExcel: "Excel formatında júklew (I-ShSB)",
        startBtn: "Kiriw",
        adminLoginBtn: "Admin paneline kiriw",
        leaderboardTitle: "🏆 Top-10 Reyting ⭐",
        thRank: "Orın",
        thName: "Oqıwshınıń F.A.Áa.",
        thClass: "Klass",
        thPoints: "Ball",
        thTime: "Waqıt",
        adminModalTitle: "Admin sistemasına kiriw",
        adminPassPlaceholder: "Admin parolın kiritiń",
        adminModalSubmit: "Kiriw",
        adminModalCancel: "Biykarlaw",
        incorrectPass: "Nadurıs parol!",
        adminPanelTitle: "Admin basqarıw paneli",
        adminLogoutBtn: "Paneldi jabıw",
        tabQuestions: "Sorawlar basqarıwı",
        tabResults: "Oqıwshılar nátiyjeleri",
        tabSettings: "Sazlamalar",
        tabQr: "QR-kod alıw",
        tabSecurity: "Qáwipsizlik",
        secTitle: "Qáwipsizlik sazlamaları",
        secShowAnswersTitle: "Nátiyjelerde juwaptı kórsetiw",
        secShowAnswersDesc: "Test juwmaqlarında oqıwshı qátelik qılǥan sorawlardıń durıs juwapları dizimin kóre alama?",
        hiddenAnswersMsg: "Qáwipsizlik kózqarasınan durıs juwaplar jasırılǥan.",
        settingsTeachersTitle: "Oqıwshılar ushın waqtınshalıq ruqsatnamalar",
        settingsTeachersHint: "Oqıtıwshılar óz pánine soraw qosıwı hám nátiyjelerdi kóriwi ushın waqtınshalıq parol (token) jaratıń.",
        lblTeacherName: "Oqıwshınıń F.A.Áa.:",
        lblTeacherSubject: "Pándi saylań:",
        lblTeacherExpire: "Ámel qılıw múddeti:",
        exp2h: "2 saat",
        exp1d: "1 kún",
        exp1w: "1 hápte",
        exp1m: "1 ay",
        btnGenerateToken: "Parol jaratıw",
        thTeacherName: "F.A.Áa.",
        thTeacherSubject: "Pán",
        thTeacherToken: "Parol",
        thTeacherExpire: "Juwmaqlanıw waqtı",
        thTeacherAction: "Ámel",
        alertTokenExpired: "Bul paroldıń ámel qılıw mГєddeti tawsılǥan!",
        manualAddTitle: "Jańa soraw qosıw (Qoldan)",
        qTextPlaceholder: "Soraw teksti",
        optAPlaceholder: "Variant A",
        optBPlaceholder: "Variant B",
        optCPlaceholder: "Variant C",
        optDPlaceholder: "Variant D",
        lblCorrect: "Durıs juwap:",
        optA: "Variant A",
        optB: "Variant B",
        optC: "Variant C",
        optD: "Variant D",
        lblPoints: "Soraw balı:",
        saveQBtn: "Sorawdı saqlaw",
        wordImportTitle: "Word fayldan juklew (.docx)",
        wordImportHint: "Word faylıńız tómendegi shablonǥa sáykes keliwi kerek:",
        btnImport: "Sorawlardı import qılıw",
        questionsListTitle: "Barlıq sorawlar",
        resultsTableTitle: "Nátiyjeler kestesi",
        lblFilterClass: "Klass boyınsha filter:",
        filterAll: "Barlıǥı",
        btnExportCsv: "Excel formatında juklep alıw (CSV)",
        btnClearResults: "Barlıq natiyjelerdi tazalaw",
        thScore: "Toplanǥan ball",
        thPercent: "Procent",
        thBlocks: "Bloklar sanı",
        settingsGeneralTitle: "Test ulıwma sazlamaları",
        lblTestDuration: "Test waqtı (minutta):",
        settingsTelegramTitle: "Sazlamalar",
        settingsTelegramHint: "Hár bir oqıwshı testti juwmaqlaǥannan keyin, onıń natiyjeleri Telegram arqalı sizge jiberiledi.",
        lblTgBotToken: "Telegram Bot Token:",
        lblTgChatId: "Telegram Chat ID (Gruppa yamasa jeke ID):",
        alertSaved: "Barlıq sazlamalar saqlandı!",
        btnSaveSettings: "Barlıq sazlamalardı saqlaw",
        qrTitle: "Proekt QR-kodı",
        qrHint: "Usı QR-kod járdeminde oqıwshılar testke tez kiriwi mГєmkin.",
        downloadQr: "QR-kodtı juklep alıw (PNG)",
        quizInfoQuestion: "Soraw",
        quizInfoPoints: "ball",
        nextBtn: "Keyingi soraw",
        testFinishedTitle: "Test Juwmaqlandı",
        certCongrats: "Qutlıqlaymız! Siz joqarı nátiyje kórsettińiz.",
        certInfo: "Siz óz sertifikatıńızdı júklep alıwıńız múmkin.",
        btnDownloadCert: "Sertifikattı juklep alıw (PNG)",
        errorReviewTitle: "Qáteler ústinde islew",
        btnBackToHome: "Tiykarǥı betke qaytıw",
        lockWarningTitle: "SIZ BLOKLANDÍŃÍZ!",
        lockWarningText: "Sistemadan paydalanıw qaǥıydaları buzıldı (ekran ózgertildi yamasa tolıq ekran rejiminen shıǵıldı).",
        lockAdminNote: "Siz test qaǥıydasın buzdińız! Oqıtıwshı parolin kiritiń:",
        lockPassPlaceholder: "Oqıtıwshı paroli",
        lockBtnUnlock: "Ashıw",
        lblUnblockPin: "Bloktan shıǵarıw paroli:",

        alertDuration: "Iltımas, test waqtın durıs kiritiń!",
        teacherPinSaved: "Siziń pánińiz ushın sazlamalar tabıslı saqlandı!",
        teacherTimerPrefix: "Sizge berilgen ruqsat etilgen waqıt juwmaqlanıwına qaldı:",
        teacherTimerMin: "minut",
        teacherTimerSecs: "sekund",
        adminLoginLink: "Oqıtıwshılar hám Admin kiriwi",
        backToStudentLogin: "Oqıwshı aynasına qaytıw",
        teacherPinSetterTitle: "Pánińiz ushın PIN-kod hám Test waqtın belgileń",
        lblTeacherPin: "Oqıwshılar ushın PIN-kod:",
        lblTeacherDuration: "Test dawamiylıǥı (minut):",
        btnSaveTeacherSettings: "Sazlamalardı saqlaw",
        timeUpAlert: "Siziń waqtınshalıq ruxsatnamańız óz juwmaǥına jetti!",
        alertDetails: "Iltimas, atıńız hám klasıńızdı tolıq kiritiń!",
        alertNoQuestions: "Sorawlar tabılmadı!",
        alertFields: "Barlıq orınlardı toltırıń!",
        alertAdded: "Soraw qosıldı!",
        alertSelectFile: "Iltimas, dáslep Word (.docx) faylın saylań!",
        alertReadError: "Fayldı oqıwda qátelik júz berdi!",
        alertConfirmClear: "Nátiyjelerdi tolıq Гіshirmekshisiz be?",
        alertNoExport: "Eksport qılıw ushın nátiyjeler tabılmadı!",
        alertImportEmpty: "Fayl ishinen sáykes formattaǵı sorawlar tabılmadı! Iltimas shablondı tekseriń.",
        alertConfirmDelete: "Bul sorawdı óshirmekshisiz be?",
        alertTimeout: "Waqıt tamamlandı! Test avtomatik juwmaqlanadı.",
        alertImportSuccess: "Tabıslı juklendi:",
        alertImportSuccess2: " taza soraw qosıldı!",
        btnDelete: "Óshiriw",
        unknown: "Belgisiz",
        times: "márte",
        noResults: "Házirshe nátiyjeler tabılmadı.",
        emptyLeaderboard: "Reyting kestesi bos.",
        notAnswered: "Juwap berilmegen",
        yourAnswer: "Siz tańlaǵan juwap:",
        noMistakes: "Qutlıqlaymız! Hesh qanday qátege jol qoyılmadı.",
        studentLabel: "Oqıwshı:",
        percentageLabel: "Procent kórsetkishi:",
        timeSpent: "Sarp etilgen waqıt:",
        violations: "Qaǵıyda buzıwshılıqlar (Bloklar):",
        analysisLabel: "Analiz:",
        totalLimit: "Ulıwma limit:",
        min: "min",
        certTitle: "SERTIFIKAT",
        certGivenTo: "Usı sertifikat tapsırıladı:",
        studentOfClass: "-klass oqıwshısı",
        certText1: "ShSB imtixannan joqarı natiyje",
        certText2: "arnawlı pánler boyınsha bekkem bilimin kórsetkeni ushın.",
        dateLabel: "Sáne:",
        portalAdmin: "Mektep adminstraciyası",
        examResult: "IMTIXAN NÁTIYJESI°",
        analysisEx: "Joqarı dáreje! Siz temanı tolıq ózlestirgensiz.",
        analysisGood: "Jaqsı natiyje. Bilimińizdi jáne de bekkemlewińiz múmkin.",
        analysisSat: "Qanaatlandırarlıq. Tákirarlaw kóbirek talap etiledi.",
        analysisBad: "Tómen nátiyje. Iltimas, sabaqlıqtı qaytadan oqıp shıǥıń.",
        lblFilterQuarter: "Sherek:",
        qAll: "Barlıq sherekler",
        q1: "I sherek",
        q2: "II sherek",
        q3: "III sherek",
        q4: "IV sherek",
        analyticsTitle: "Sherek analizi (Kognitiv dárejeler)",
        lblCognitive: "Kognitiv dáreje:",
        statTotalStudents: "Oqıwshılar sanı",
        statAvgScore: "Ortasha kórsetkish (%)",
        statQuality: "Sapa kórsetkishi (70%+)",
        lblQFormat: "Soraw formatı:",
        fmtClosed: "Jabıq test (A,B,C,D)",
        fmtOpen: "Ashıq soraw (Jazba)",
        lblOpenAnswer: "Durıs juwap (Gilt sóz):",
        phOpenAnswer: "Juwabıńızdı kiritiń...",
        lblWritten: "Jazba",
        comparisonTitle: "Eki sherekti óz-ara analiz qılıw",
        btnCompare: "Analiz qılıw",
        compIncreased: "ǵa ÓSTI°",
        compDecreased: "ǵa PÁSEYDI",
        compSame: "ÓZGERISSIZ qaldı",
        compConclusion: "Pedagogikalıq analiz:",
        compConclusionGood: "Jaqsı nátiyje, qosımsha sabaqlar óz paydasın bermekte.",
        compConclusionBad: "Qáweterli jaǥday, ózlestiriw tómenlegen. Qosımsha ilajlar kóriw zárúr.",
        compConclusionNeutral: "Ózlestiriw turaqlı, biraq ósiw ústinde islew usınıs etiledi.",
        subjectPlaceholder: "Pándi saylań",
                subjOzbek: "Ózbek tili",
        subjSanat: "ART",
        subjRus: "Rus tili",
        subjIngliz: "Inglis tili",
        subjTabiiy: "Tábiiy pán",
        subjOzbTarix: "Ózbekstan tariyxi",
        subjJahonTarix: "Jahan tariyxi",
        subjQorTarix: "Qaraqalpaqstan tariyxi",
        subjAdabiyot: "Ádebiyat",
        subjGeografiya: "Geografiya",
        subjTexnologiya: "Texnologiya",
        subjAlgebra: "Algebra",
        subjGeometriya: "Geometriya",
        settingsPinsTitle: "Pánler hám PIN-kodlar",
        settingsPinsHint: "Oqıwshılar testti baslawı ushın hár bir pánge arnawlı PIN-kod ornatıń.",
        settingsGeminiTitle: "Gemini AI sazlamaları",
        settingsGeminiHint: "Pedagogik analiz ótkeriw ushın Google Gemini API giltin kiritiń.",
        lblGeminiKey: "Gemini AI API Gilti:",
        btnAnalyzeAI: "Gemini AI analizi",
        aiAnalyzing: "Gemini AI klass nátiyjelerin hám kognitivlik dárejelerin analiz etpekte...",
        btnCloseAI: "Nátiyjeni jabıw",
        lblTargetClass: "Klasstı belgilew:",
        alertNoClassTest: "Bul klass ushın test tabilmadı!",
        lblSelectStudent: "Oqıwshını tańlań:",
        selStudent: "Oqıwshını tańlań...",
        btnViewDetails: "Tolıq kóriw",
        btnCloseDetails: "Jabıw",
        lblCorrectAnswer: "Durıs juwap",
        lblStudentAnswer: "Oqıwshınıń juwabı",
        aiAnalysisTitle: "Gemini AI Analizi",
        thSubject: "Pán",
        alertWrongPin: "Qáte! Bul pán ushın PIN-kod qáte kiritildi.",
        alertGeminiNoKey: "Qáte! Iltimas, Sazlamalar bóliminen Gemini API giltin kiritiń.",
        geminiLoading: "Gemini AI analiz qılmaqta, iltimas kútiń...",
        lblTestType: "Test túri:",
        testTypeBSB: "BSB (Bap boyınsha bahalaw)",
        testTypeCHSB: "ShSB (Shereklik boyınsha bahalaw)",
        lblUploadImage: "Súwret júklew (Iqtıyariy)",
        instructionRules: "Test qaǥıydaları:",
        rule1: "Testti baslaǵannan soń waqıt artqa esaplanıwı baslanadı.",
        rule2: "Betti jańalaw (Refresh) yamasa jabıw qadaǵan etiledi.",
        rule3: "Jabıq testlerde tek bir durıs juwaptı belgileń, ashıq sorawlarda bolsa juwaptı klaviaturada qolda jazıń.",
        btnBeginTest: "Testti baslaw",
        lblTime: "Test dawamiylıǥı:",
        lblCount: "Sorawlar sanı:",
        adminLogout: "Shıǵıw",
        tabQR: "QR Kod",
        addQTitle: "Qoldan soraw qosıw",
        lblCorrectAns: "Durıs:",
        btnAddQuestion: "Sorawdı qosıw",
        wordUploaderTitle: "Word (Docx) juklew",
        wordUploaderInfo: "Fayl tómendegi formatda bolıwı kerek:",
        btnUploadWord: "Bazaǵa qosıw",
        dbQuestionsTitle: "Bazada:",
        dbQuestionsCount: " soraw",
        teacherTokensTitle: "Oqıtıwshılar ushın waqtınshalıq ruqsatnamalar",
        teacherTokensHint: "Oqıtıwshılarǵa tek óz pánin basqarıw huquqın beretuǵın waqtınshalıq paroller (tokenler) jaratıń.",
        lblDefaultTime: "Standart test dawamiylıǵı (minut):",
        settingsTgHint: "Oqıwshı testti juwmaqlaǵannan keyin, nátiyje avtomatik Telegram arqalı jiberiledi.",
        lblTgToken: "Bot Token:",
        lblTgChatId: "Chat ID (yaki Gruppa ID):",
        secAnswersTitle: "Test juwapları (Oqıwshıǵa)",
        secAnswersLabel: "Test sońında durıs juwaplardı oqıwshıǵa kórsetiw:",
    btnShowAnswersOn: "Juwaplardı kórsetiw: QOSILǴAN",
    btnShowAnswersOff: "Juwaplardı kórsetiw: ÓSHIRILGEN",
    btnShowAnswersOn: "Juwaplardı kórsetiw: QOSÍLGAN",
    btnShowAnswersOff: "Juwaplardı kórsetiw: ÓSHIRILGEN",
        secAnswersHint: "Qáwipsizlik kózqarasınan durıs juwaplar jasırılǵan.",
        qrCodeTitle: "Platforma ushın QR Kod",
        qrCodeHint: "Usı QR kod arqalı oqıwshılar testke tez kiriwi múmkin.",
        btnDownloadQR: "QR Kodtı juklep alıw (PNG)",
        phQuestionText: "Soraw tekstin usı jerge jazıń...",
        phOptA: "A variant...",
        phOptB: "B variant...",
        phOptC: "C variant...",
        phOptD: "D variant...",
        lblAdminQuarter: "Sherek:",
        settingsSavedMsg: "Barlıq sazlamalar saqlandı!",
        alertFillFields: "Barlıq orınlardı toltırıń!",
        confirmDeleteQ: "Bul sorawdı óshirmekshisiz be?",
        confirmClearResults: "Nátiyjelerdi tolıq óshirmekshisiz be?",
        msgResultsCleared: "Nátiyjeler tazalandı!",
        msgQuestionDeleted: "Soraw óshirildi!",
        btnFinishQuiz: "Juwmaqlaw",
        thPercentage: "Procent",
        thDate: "Sáne",
        alertGeminiKey: "Gemini API gilti sazlanbaǵan! Sazlamalar bóliminen kiritiń.",
        tempPasswordExpired: "Waqtınshalıq parol múddeti tamamlanǵan!",
        thExpireDate: "Amel etiw múddeti:",
        currentActiveToken: "Házirgi waqtınshalıq parol:",
        noActiveToken: "Aktiv waqtınshalıq parol joq"
    },
    en: {
        toastWarning: "Viewing code is prohibited due to system security!",
        schoolName: "Khodjeyli specialized school",
        welcomeMsg: "Welcome! Enter your details to start the test.",
        namePlaceholder: "Full Name",
        classPlaceholder: "Class / Group (e.g., 9-A, 11-B)",
        pinPlaceholder: "Enter specific PIN code",
        cogKnowing: "Knowing / Knowledge",
        cogApp: "Application",
        cogReasoning: "Reasoning",
        selClass: "Select Class",
        selQuarter: "Select Quarter",
        btnExportExcel: "Download as Excel (SA/TSA)",
        startBtn: "Login",
        adminLoginBtn: "Enter Admin Panel",
        leaderboardTitle: "🏆 Top-10 Leaderboard ⭐",
        thRank: "Rank",
        thName: "Name",
        thClass: "Class",
        thPoints: "Points",
        thTime: "Time",
        adminModalTitle: "Admin System Login",
        adminPassPlaceholder: "Enter Admin Password",
        adminModalSubmit: "Login",
        adminModalCancel: "Cancel",
        incorrectPass: "Incorrect password!",
        adminPanelTitle: "Admin Control Panel",
        adminLogoutBtn: "Close Panel",
        tabQuestions: "Questions Management",
        tabResults: "Student Results",
        tabSettings: "Settings",
        tabQr: "Get QR Code",
        tabSecurity: "Security",
        secTitle: "Security Settings",
        secShowAnswersTitle: "Show answers in results",
        secShowAnswersDesc: "Will the student be able to see the list of correct answers to the questions they got wrong at the end of the test?",
        hiddenAnswersMsg: "Correct answers are hidden for security reasons.",
        settingsTeachersTitle: "Temporary permissions for teachers",
        settingsTeachersHint: "Generate a temporary password (token) so teachers can add questions and view results for their subject.",
        lblTeacherName: "Teacher Full Name:",
        lblTeacherSubject: "Select Subject:",
        lblTeacherExpire: "Expiration time:",
        exp2h: "2 hours",
        exp1d: "1 day",
        exp1w: "1 week",
        exp1m: "1 month",
        btnGenerateToken: "Generate Password",
        thTeacherName: "Full Name",
        thTeacherSubject: "Subject",
        thTeacherToken: "Token",
        thTeacherExpire: "Expires At",
        thTeacherAction: "Action",
        alertTokenExpired: "This password has expired!",
        manualAddTitle: "Add New Question (Manual)",
        qTextPlaceholder: "Question text",
        optAPlaceholder: "Option A",
        optBPlaceholder: "Option B",
        optCPlaceholder: "Option C",
        optDPlaceholder: "Option D",
        lblCorrect: "Correct answer:",
        optA: "Option A",
        optB: "Option B",
        optC: "Option C",
        optD: "Option D",
        lblPoints: "Question points:",
        saveQBtn: "Save Question",
        wordImportTitle: "Upload from Word (.docx)",
        wordImportHint: "Your Word file must match the following template:",
        btnImport: "Import Questions",
        questionsListTitle: "Available Questions",
        resultsTableTitle: "Results Table",
        lblFilterClass: "Filter by Class:",
        filterAll: "All",
        btnExportCsv: "Export as Excel (CSV)",
        btnClearResults: "Clear All Results",
        thScore: "Score",
        thPercent: "Percentage",
        thBlocks: "Blocks",
        settingsGeneralTitle: "General Test Settings",
        lblTestDuration: "Test Duration (minutes):",
        settingsTelegramTitle: "Settings",
        settingsTelegramHint: "After each student finishes the test, their results will be sent to you via Telegram.",
        lblTgBotToken: "Telegram Bot Token:",
        lblTgChatId: "Telegram Chat ID (Group or Personal ID):",
        btnSaveSettings: "Save All Settings",
        qrTitle: "Project QR Code",
        qrHint: "Students can quickly access the test using this QR code.",
        downloadQr: "Download QR Code (PNG)",
        quizInfoQuestion: "Question",
        quizInfoPoints: "points",
        nextBtn: "Next Question",
        testFinishedTitle: "Test Finished",
        certCongrats: "Congratulations! You achieved a high score.",
        certInfo: "You can download your certificate.",
        btnDownloadCert: "Download Certificate (PNG)",
        errorReviewTitle: "Review Mistakes",
        btnBackToHome: "Back to Home",
        lockWarningTitle: "YOU ARE BLOCKED!",
        lockWarningText: "System usage rules violated (screen changed or exited full screen mode).",
        lockAdminNote: "You violated the test rules! Enter the teacher's password to continue:",
        lockPassPlaceholder: "Teacher password",
        lockBtnUnlock: "Unlock",
        lblUnblockPin: "Unblock PIN:",
        
        alertDuration: "Please enter a valid test duration!",
        teacherPinSaved: "Settings for your subject have been saved successfully!",
        teacherTimerPrefix: "Your temporary permission expires in:",
        teacherTimerMins: "minutes",
        teacherTimerSecs: "seconds",
        adminLoginLink: "Teacher and Admin Login",
        backToStudentLogin: "Back to Student Screen",
        teacherPinSetterTitle: "Set PIN Code and Test Time for your subject",
        lblTeacherPin: "PIN Code for students:",
        lblTeacherDuration: "Test duration (minutes):",
        btnSaveTeacherSettings: "Save Settings",
        timeUpAlert: "Your temporary permission has expired!",
        alertDetails: "Please enter your full name and class!",
        alertNoQuestions: "No questions available! Please contact the admin.",
        alertFields: "Fill in all fields!",
        alertAdded: "Question added!",
        alertSelectFile: "Please select a Word (.docx) file first!",
        alertReadError: "Error reading the file!",
        alertConfirmClear: "Are you sure you want to completely clear all results?",
        alertNoExport: "No results available to export!",
        alertImportEmpty: "No questions matching the format were found in the file! Please check the template.",
        alertConfirmDelete: "Are you sure you want to delete this question?",
        alertTimeout: "Time's up! The test will automatically finish.",
        alertImportSuccess: "Successfully loaded:",
        alertImportSuccess2: "new questions added!",
        btnDelete: "Delete",
        unknown: "Unknown",
        times: "times",
        noResults: "No results available yet.",
        emptyLeaderboard: "Leaderboard is empty.",
        notAnswered: "Not answered",
        yourAnswer: "Your answer:",
        noMistakes: "Congratulations! No mistakes were made.",
        studentLabel: "Student:",
        percentageLabel: "Percentage:",
        timeSpent: "Time spent:",
        violations: "Violations (Blocks):",
        analysisLabel: "Analysis:",
        totalLimit: "Total limit:",
        min: "min",
        certTitle: "CERTIFICATE OF ACHIEVEMENT",
        certGivenTo: "This certificate is awarded to:",
        studentOfClass: "student of class",
        certText1: "For achieving a high score",
        certText2: "in the examination and demonstrating strong knowledge.",
        dateLabel: "Date:",
        portalAdmin: "Portal Administration",
        examResult: "EXAM RESULT",
        analysisEx: "Excellent! You have mastered the subject perfectly.",
        analysisGood: "Good result. You can further consolidate your knowledge.",
        analysisSat: "Satisfactory. More revision is required.",
        analysisBad: "Low result. Please review the textbook again.",
        lblFilterQuarter: "Quarter:",
        qAll: "All quarters",
        q1: "I quarter",
        q2: "II quarter",
        q3: "III quarter",
        q4: "IV quarter",
        analyticsTitle: "Quarterly Analytics (Cognitive Levels)",
        lblCognitive: "Cognitive level:",
        statTotalStudents: "Total Students",
        statAvgScore: "Average Score (%)",
        statQuality: "Quality Indicator (70%+)",
        lblQFormat: "Question format:",
        fmtClosed: "Closed test (A,B,C,D)",
        fmtOpen: "Open question (Written)",
        lblOpenAnswer: "Correct answer text (Keyword):",
        phOpenAnswer: "Enter your answer...",
        lblWritten: "Written",
        comparisonTitle: "Compare Two Quarters",
        btnCompare: "Analyze",
        compIncreased: "INCREASED by",
        compDecreased: "DECREASED by",
        compSame: "remained UNCHANGED",
        compConclusion: "Pedagogical Conclusion:",
        compConclusionGood: "Good result, additional lessons are showing positive effects.",
        compConclusionBad: "Concerning situation, individual work with students is required.",
        compConclusionNeutral: "No change, efforts need to be increased.",
        subjectPlaceholder: "Select Subject",
        pinPlaceholder: "Enter specific PIN code",
                subjOzbek: "Uzbek Language",
        subjSanat: "ART",
        subjRus: "Russian Language",
        subjIngliz: "English Language",
        subjTabiiy: "Natural Science",
        subjOzbTarix: "History of Uzbekistan",
        subjJahonTarix: "World History",
        subjQorTarix: "History of Karakalpakstan",
        subjAdabiyot: "Literature",
        subjGeografiya: "Geography",
        subjTexnologiya: "Technology",
        subjAlgebra: "Algebra",
        subjGeometriya: "Geometry",
        settingsPinsTitle: "Subjects and PIN Codes",
        settingsPinsHint: "Set a specific PIN code for each subject to allow students to start the test.",
        settingsGeminiTitle: "Gemini AI Settings",
        settingsGeminiHint: "Enter your Google Gemini API key to run pedagogical analysis.",
        lblGeminiKey: "Gemini AI API Key:",
        btnAnalyzeAI: "Gemini AI Analysis вњЁ",
        aiAnalyzing: "Gemini AI is analyzing class results and cognitive levels...",
        btnCloseAI: "Close Result",
        lblTargetClass: "Target Class:",
        alertNoClassTest: "No test found for this class!",
        lblSelectStudent: "Select Student:",
        selStudent: "Select Student...",
        btnViewDetails: "View Details",
        btnCloseDetails: "Close",
        lblCorrectAnswer: "Correct Answer",
        lblStudentAnswer: "Student's Answer",
        aiAnalysisTitle: "Gemini AI Analysis",
        thSubject: "Subject",
        alertWrongPin: "Error! Incorrect PIN code for this subject.",
        alertGeminiNoKey: "Error! Please enter the Gemini API key in the Settings section.",
        geminiLoading: "Gemini AI is analyzing, please wait...",
        lblTestType: "Test Type:",
        testTypeBSB: "SA (Summative Assessment)",
        testTypeCHSB: "TSA (Term Summative Assessment)",
        lblUploadImage: "Upload Image",
        instructionRules: "Test Rules:",
        rule1: "The timer will start counting down once you begin the test.",
        rule2: "Refreshing or closing the page is prohibited (results may be lost).",
        rule3: "For multiple-choice questions, select only one correct answer. For open questions, type your answer using the keyboard.",
        btnBeginTest: "Start Test",
        lblTime: "Time:",
        lblCount: "Question count:",
        adminLogout: "Logout",
        tabQR: "QR Code",
        addQTitle: "Add Question Manually",
        lblCorrectAns: "Correct:",
        btnAddQuestion: "Add Question",
        wordUploaderTitle: "Upload Word (Docx)",
        wordUploaderInfo: "The file must follow this strict format:",
        btnUploadWord: "Add to Database",
        dbQuestionsTitle: "In database:",
        dbQuestionsCount: "questions",
        teacherTokensTitle: "Temporary teacher permissions",
        teacherTokensHint: "Generate temporary passwords (tokens) so teachers can manage only their subject.",
        lblDefaultTime: "Default test duration (minutes):",
        settingsTgHint: "When a student finishes a test, the result is sent to your Telegram bot or group.",
        lblTgToken: "Bot Token:",
        lblTgChatId: "Chat ID (or Group ID):",
        secAnswersTitle: "Test Answers (For Students)",
        secAnswersLabel: "Test yakunida to'g'ri javoblarni o'quvchiga ko'rsatish:",
    btnShowAnswersOn: "Javoblarni ko'rsatish: YOQILGAN",
    btnShowAnswersOff: "Javoblarni ko'rsatish: O'CHIRILGAN",
        secAnswersHint: "Correct answers are hidden for security reasons.",
        qrCodeTitle: "Platform QR Code",
        qrCodeHint: "Students can quickly access the test using this QR code.",
        btnDownloadQR: "Download QR Code (PNG)",
        phQuestionText: "Enter question text here...",
        phOptA: "Option A...",
        phOptB: "Option B...",
        phOptC: "Option C...",
        phOptD: "Option D...",
        lblAdminQuarter: "Quarter:",
        settingsSavedMsg: "All settings saved!",
        alertFillFields: "Please fill in all fields!",
        confirmDeleteQ: "Delete this question?",
        confirmClearResults: "Clear all results?",
        msgResultsCleared: "Results cleared!",
        msgQuestionDeleted: "Question deleted!",
        btnFinishQuiz: "Finish",
        thPercentage: "Percentage",
        thDate: "Date",
        alertGeminiKey: "Gemini API key is not configured! Enter it in Settings.",
        tempPasswordExpired: "Temporary password has expired!",
        thExpireDate: "Expiration date:",
        currentActiveToken: "Current temporary password:",
        noActiveToken: "No active temporary password"
    }
};

let currentLang = localStorage.getItem('quiz_lang') || 'uz';

function t(key) {
    return translations[currentLang][key] || key;
}

function applyTranslations() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[currentLang] && translations[currentLang][key]) {
            el.innerHTML = translations[currentLang][key];
        }
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (translations[currentLang] && translations[currentLang][key]) {
            el.setAttribute('placeholder', translations[currentLang][key]);
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    applyTranslations();

    const langBtns = document.querySelectorAll('.lang-btn');
    langBtns.forEach(btn => {
        if (btn.getAttribute('data-lang') === currentLang) {
            btn.classList.add('active');
        } else {
            btn.classList.remove('active');
        }

        btn.addEventListener('click', (e) => {
            langBtns.forEach(b => b.classList.remove('active'));
            e.target.classList.add('active');
            currentLang = e.target.getAttribute('data-lang');
            localStorage.setItem('quiz_lang', currentLang);
            applyTranslations();
            
            // Re-render components if methods are available in global scope
            if (typeof renderLeaderboard === 'function' && !document.getElementById('auth-screen').classList.contains('hidden')) {
                renderLeaderboard();
            }
            if (typeof renderQuestionsList === 'function' && !document.getElementById('admin-panel').classList.contains('hidden')) {
                renderQuestionsList();
                if (typeof renderResultsTable === 'function') {
                    renderResultsTable();
                }
            }
        });
    });
});


