const translations = {
    uz: {
        toastWarning: "Tizim xavfsizligi tufayli kodni ko'rish taqiqlanadi!",
        schoolName: "Xo'jayli tumani ixtisoslashtirilgan maktabi",
        welcomeMsg: "Xush kelibsiz! Testni boshlash uchun ma'lumotlarni kiriting.",
        namePlaceholder: "F.I.SH.",
        classPlaceholder: "Sinf / Guruh (Masalan: 9-A, 11-B)",
        pinPlaceholder: "Maxsus kod (PIN)",
        cogKnowing: "Bilish",
        cogApp: "Qo'llash",
        cogReasoning: "Mulohaza qilish",
        selClass: "Sinfni tanlang",
        selQuarter: "Chorakni tanlang",
        btnExportExcel: "Excel formatda yuklash (BSB/CHSB)",
        startBtn: "Testni Boshlash",
        adminLoginBtn: "Admin paneliga kirish",
        leaderboardTitle: "🏆 Top-10 Reyting",
        thRank: "O'rin",
        thName: "F.I.SH.",
        thClass: "Sinf",
        thPoints: "Ball",
        thTime: "Vaqt",
        adminModalTitle: "Admin Tizimiga Kirish",
        adminPassPlaceholder: "Admin parolini kiriting",
        adminModalSubmit: "Kirish",
        adminModalCancel: "Bekor qilish",
        incorrectPass: "Noto'g'ri parol!",
        adminPanelTitle: "Admin Boshqaruv Paneli",
        adminLogoutBtn: "Panelni yopish",
        tabQuestions: "Savollar boshqaruvi",
        tabResults: "O'quvchilar Natijalari",
        tabSettings: "Sozlamalar",
        tabQr: "QR-kod olish",
        tabSecurity: "Xavfsizlik",
        secTitle: "Xavfsizlik Sozlamalari",
        secShowAnswersTitle: "Natijalarda javoblarni ko'rsatish",
        secShowAnswersDesc: "Test yakunida o'quvchi xato qilgan savollarning to'g'ri javoblari ro'yxatini ko'ra oladimi?",
        hiddenAnswersMsg: "Xavfsizlik nuqtai nazaridan to'g'ri javoblar yashirilgan.",
        settingsTeachersTitle: "O'qituvchilar uchun vaqtinchalik ruxsatnomalar",
        settingsTeachersHint: "O'qituvchilar o'z faniga savol qo'shishi va natijalarni ko'rishi uchun vaqtinchalik parol (token) yarating.",
        lblTeacherName: "O'qituvchi F.I.SH:",
        lblTeacherSubject: "Fanni tanlang:",
        lblTeacherExpire: "Amal qilish muddati:",
        exp2h: "2 soat",
        exp1d: "1 kun",
        exp1w: "1 hafta",
        exp1m: "1 oy",
        btnGenerateToken: "Parol yaratish",
        thTeacherName: "F.I.SH.",
        thTeacherSubject: "Fan",
        thTeacherToken: "Parol",
        thTeacherExpire: "Tugash vaqti",
        thTeacherAction: "Amal",
        alertTokenExpired: "Ushbu parolning amal qilish muddati tugagan!",
        manualAddTitle: "Yangi savol qo'shish (Qo'lda)",
        qTextPlaceholder: "Savol matni",
        optAPlaceholder: "Variant A",
        optBPlaceholder: "Variant B",
        optCPlaceholder: "Variant C",
        optDPlaceholder: "Variant D",
        lblCorrect: "To'g'ri javob:",
        optA: "Variant A",
        optB: "Variant B",
        optC: "Variant C",
        optD: "Variant D",
        lblPoints: "Savol balli:",
        saveQBtn: "Savolni saqlash",
        wordImportTitle: "Word fayldan yuklash (.docx)",
        wordImportHint: "Word faylingiz quyidagi shablonga mos bo'lishi kerak:",
        btnImport: "Savollarni import qilish",
        questionsListTitle: "Mavjud savollar",
        resultsTableTitle: "Natijalar jadvali",
        lblFilterClass: "Sinf bo'yicha filter:",
        filterAll: "Barchasi",
        btnExportCsv: "Excel formatda yuklab olish (CSV)",
        btnClearResults: "Barcha natijalarni tozalash",
        thScore: "To'plangan ball",
        thPercent: "Foiz",
        thBlocks: "Bloklar soni",
        settingsGeneralTitle: "Test umumiy sozlamalari",
        lblTestDuration: "Test vaqti (daqiqada):",
        settingsTelegramTitle: "Telegram bot sozlamalari (Bildirishnoma va zaxira)",
        settingsTelegramHint: "Har bir o'quvchi testni tugatgandan so'ng, uning natijalari Telegram orqali sizga yuboriladi.",
        lblTgBotToken: "Telegram Bot Token:",
        lblTgChatId: "Telegram Chat ID (Guruh yoki shaxsiy ID):",
        btnSaveSettings: "Barcha sozlamalarni saqlash",
        qrTitle: "Loyiha QR-kodi",
        qrHint: "Ushbu QR-kod yordamida o'quvchilar testga tezkor kirishlari mumkin.",
        downloadQr: "QR-kodni yuklab olish (PNG)",
        quizInfoQuestion: "Savol",
        quizInfoPoints: "ball",
        nextBtn: "Keyingi savol",
        testFinishedTitle: "Test Yakunlandi",
        certCongrats: "Tabriklaymiz! Siz yuqori natija ko'rsatdingiz.",
        certInfo: "Siz o'z sertifikatingizni yuklab olishingiz mumkin.",
        btnDownloadCert: "Sertifikatni yuklab olish (PNG)",
        errorReviewTitle: "Xatolar ustida ishlash",
        btnBackToHome: "Asosiy sahifaga qaytish",
        lockWarningTitle: "SIZ BLOKLANDINGIZ!",
        lockWarningText: "Tizimdan foydalanish qoidalari buzildi (ekran o'zgartirildi yoki to'liq ekran rejimidan chiqildi).",
        lockAdminNote: "Blokdan chiqarish uchun admin parolini kiriting:",
        lockPassPlaceholder: "Admin paroli",
        lockBtnUnlock: "Unlock",
        
        // JS specific
        alertDuration: "Iltimos, test vaqtini to'g'ri kiriting!",
        teacherPinSaved: "Faningiz uchun sozlamalar muvaffaqiyatli saqlandi!",
        teacherTimerPrefix: "Sizning ruxsatnomangiz tugashiga qoldi:",
        teacherTimerMins: "daqiqa",
        teacherTimerSecs: "soniya",
        adminLoginLink: "O'qituvchilar va Admin kirishi",
        backToStudentLogin: "O'quvchi oynasiga qaytish",
        teacherPinSetterTitle: "Faningiz uchun PIN-kod va Test vaqtini belgilang",
        lblTeacherPin: "O'quvchilar uchun PIN-kod:",
        lblTeacherDuration: "Test davomiyligi (daqiqa):",
        btnSaveTeacherSettings: "Sozlamalarni saqlash",
        timeUpAlert: "Sizning vaqtinchalik ruxsatnomangiz o'z nihoyasiga yetdi!",
        alertDetails: "Iltimos, ismingiz va sinfingizni to'liq kiriting!",
        alertNoQuestions: "Savollar mavjud emas! Iltimos, admin bilan bog'laning.",
        alertFields: "Barcha maydonlarni to'ldiring!",
        alertAdded: "Savol qo'shildi!",
        alertSelectFile: "Iltimos, avval Word (.docx) faylini tanlang!",
        alertReadError: "Faylni o'qishda xatolik yuz berdi!",
        alertConfirmClear: "Natijalarni butunlay o'chirmoqchimisiz?",
        alertNoExport: "Eksport qilish uchun natijalar mavjud emas!",
        alertImportEmpty: "Fayl ichidan mos formatdagi savollar topilmadi! Iltimos shablonni tekshiring.",
        alertConfirmDelete: "Ushbu savolni o'chirib tashlamoqchimisiz?",
        alertTimeout: "Vaqt tugadi! Test avtomatik yakunlanadi.",
        alertImportSuccess: "Muvaffaqiyatli yuklandi:",
        alertImportSuccess2: "ta yangi savol qo'shildi!",
        btnDelete: "O'chirish",
        unknown: "Noma'lum",
        times: "marta",
        noResults: "Hozircha natijalar mavjud emas.",
        emptyLeaderboard: "Reyting jadvali bo'sh.",
        notAnswered: "Javob berilmagan",
        yourAnswer: "Siz tanlagan javob:",
        noMistakes: "Tabriklaymiz! Hech qanday xatoga yo'l qo'yilmadi.",
        studentLabel: "Talaba:",
        percentageLabel: "Foiz ko'rsatkichi:",
        timeSpent: "Sarflangan vaqt:",
        violations: "Qoidabuzarliklar (Bloklar):",
        analysisLabel: "Tahlil:",
        totalLimit: "Jami limit:",
        min: "daq",
        certTitle: "MAQTOV YORLIG'I",
        certGivenTo: "Ushbu sertifikat topshiriladi:",
        studentOfClass: "-sinf o'quvchisi",
        certText1: "Portalimizdagi imtihondan yuqori natija",
        certText2: "maxsus fanlar bo'yicha mustahkam bilimini namoyon etganligi uchun.",
        dateLabel: "Sana:",
        portalAdmin: "Portal Ma'muriyati",
        examResult: "IMTIHON NATIJASI",
        analysisEx: "A'lo daraja! Siz mavzuni mukammal o'zlashtirgansiz.",
        analysisGood: "Yaxshi natija. Bilimingizni yanada mustahkamlashingiz mumkin.",
        analysisSat: "Qoniqarli. Takrorlash ko'proq talab etiladi.",
        analysisBad: "Past natija. Iltimos, darslikni qaytadan o'qib chiqing.",
        lblFilterQuarter: "Chorak:",
        qAll: "Barcha choraklar",
        q1: "I chorak",
        q2: "II chorak",
        q3: "III chorak",
        q4: "IV chorak",
        analyticsTitle: "Choraklik Tahlil (Kognitiv darajalar)",
        lblCognitive: "Kognitiv daraja:",
        statTotalStudents: "O'quvchilar soni",
        statAvgScore: "O'rtacha ko'rsatkich (%)",
        statQuality: "Sifat ko'rsatkichi (70%+)",
        lblQFormat: "Savol formati:",
        fmtClosed: "Yopiq test (A,B,C,D)",
        fmtOpen: "Ochiq savol (Yozma)",
        lblOpenAnswer: "To'g'ri javob matni (Kalit so'z):",
        phOpenAnswer: "Javobingizni kiriting...",
        lblWritten: "Yozma",
        comparisonTitle: "Ikki chorakni o'zaro tahlil qilish",
        btnCompare: "Tahlil qilish",
        compIncreased: "ga O'SDI",
        compDecreased: "ga PASAYDI",
        compSame: "O'ZGARISHSZ qoldi",
        compConclusion: "Pedagogik tahlil:",
        compConclusionGood: "Yaxshi natija, qo'shimcha darslar o'z samarasini bermoqda.",
        compConclusionBad: "Xavotirli holat, o'zlashtirish tushib ketgan. Qo'shimcha chora-tadbirlar ko'rish zarur.",
        compConclusionNeutral: "O'zlashtirish barqaror, ammo o'sish ustida ishlash tavsiya etiladi",
        subjectPlaceholder: "Fanni tanlang",
        pinPlaceholder: "Maxsus PIN-kodni kiriting",
        subjOnaTili: "Ona tili",
        subjMatematika: "Matematika",
        subjFizika: "Fizika",
        subjKimyo: "Kimyo",
        subjBiologiya: "Biologiya",
        subjTarix: "Tarix",
        subjHuquq: "Huquq",
        subjInformatika: "Informatika",
        settingsPinsTitle: "Fanlar va PIN-kodlar",
        settingsPinsHint: "O'quvchilar testni boshlashi uchun har bir fanga maxsus PIN-kod o'rnating.",
        settingsGeminiTitle: "Gemini AI Sozlamalari",
        settingsGeminiHint: "Pedagogik tahlil o'tkazish uchun Google Gemini API kalitini kiriting.",
        lblGeminiKey: "Gemini AI API Kaliti:",
        btnAnalyzeAI: "Gemini AI tahlili ✨",
        aiAnalyzing: "Gemini AI sinf natijalari va kognitiv darajalarni tahlil qilmoqda...",
        btnCloseAI: "Natijani yopish",
        aiAnalysisTitle: "Gemini AI Tahlili",
        thSubject: "Fan",
        alertWrongPin: "Xato! Bu fan uchun PIN-kod noto'g'ri kiritildi.",
        alertGeminiNoKey: "Xato! Iltimos, Sozlamalar bo'limidan Gemini API kalitini kiriting.",
        geminiLoading: "Gemini AI tahlil qilmoqda, iltimos kuting...",
        lblTestType: "Test turi:",
        testTypeBSB: "BSB",
        testTypeCHSB: "CHSB",
        lblUploadImage: "Rasm yuklash",
        instructionRules: "Test ishlash qoidalari:",
        rule1: "Testni boshlagandan so'ng vaqt ortga hisoblana boshlaydi.",
        rule2: "Sahifani yangilash (Refresh) yoki yopish taqiqlanadi (natija yo'qolishi mumkin).",
        rule2: "Sahifani yangilash (Refresh) yoki yopish taqiqlanadi (natija yo'qolishi mumkin).",
        rule3: "Yopiq testlarda faqat bitta to'g'ri javobni belgilang, ochiq savollarda esa javobni klaviaturada qo'lda yozing.",
        btnBeginTest: "Testni boshlash",
        lblTime: "Vaqt:",
        lblCount: "Savollar soni:"
    },
    qq: {
        toastWarning: "Sistema qawipsizligi sebepli kodti kóriw qadaǵalanadı!",
        schoolName: "Xojeli rayonı qánigelestirilgen mektebi",
        welcomeMsg: "Xosh keldińiz! Testti baslaw ushın maǵlıwmatlardı kiritiń.",
        namePlaceholder: "F.I.A.",
        classPlaceholder: "Sınıp / Gruppa (Mısalı: 9-A, 11-B)",
        pinPlaceholder: "Arnawlı kod (PIN)",
        cogKnowing: "Biliw",
        cogApp: "Qollanıw",
        cogReasoning: "Pikirlew",
        selClass: "Sınıftı saylań",
        selQuarter: "Sherekti saylań",
        btnExportExcel: "Excel formatta júklew (BBYb/ChBYb)",
        startBtn: "Testti Baslaw",
        adminLoginBtn: "Admin paneline kiriw",
        leaderboardTitle: "🏆 Top-10 Reyting",
        thRank: "Orın",
        thName: "F.A.Á.",
        thClass: "Klass",
        thPoints: "Ball",
        thTime: "Waqıt",
        adminModalTitle: "Admin Sistemasına Kiriw",
        adminPassPlaceholder: "Admin parolın kiritiń",
        adminModalSubmit: "Kiriw",
        adminModalCancel: "Biykarlaw",
        incorrectPass: "Nadurıs parol!",
        adminPanelTitle: "Admin Basqarıw Paneli",
        adminLogoutBtn: "Paneldi jabıw",
        tabQuestions: "Sorawlar basqarıwı",
        tabResults: "Oqıwshılar Nátiyjeleri",
        tabSettings: "Sazlamalar",
        tabQr: "QR-kod alıw",
        tabSecurity: "Qáwipsizlik",
        secTitle: "Qáwipsizlik Sazlawları",
        secShowAnswersTitle: "Nátiyjelerde juwapti kórsetiw",
        secShowAnswersDesc: "Test juwmaqlarında oqıwshı qátelik qılǵan sorawlardıń durıs juwapları dizimin kóre alama?",
        hiddenAnswersMsg: "Qáwipsizlik kózqarasınan durıs juwaplar jasırılǵan.",
        settingsTeachersTitle: "Oqıwshılar ushın waqtınshalıq ruxsatnamalar",
        settingsTeachersHint: "Oqıwshılar óz pánine soraw qosıwı hám nátiyjelerdi kóriwi ushın waqtınshalıq parol (token) jaratıń.",
        lblTeacherName: "Oqıwshı F.A.A:",
        lblTeacherSubject: "Pándi tańlań:",
        lblTeacherExpire: "Ámel qılıw múddeti:",
        exp2h: "2 saat",
        exp1d: "1 kún",
        exp1w: "1 hápte",
        exp1m: "1 ay",
        btnGenerateToken: "Parol jaratıw",
        thTeacherName: "F.A.A.",
        thTeacherSubject: "Pán",
        thTeacherToken: "Parol",
        thTeacherExpire: "Tawsılıw waqtı",
        thTeacherAction: "Ámel",
        alertTokenExpired: "Bul paroldıń ámel qılıw múddeti tawsılǵan!",
        manualAddTitle: "Jańa soraw qosıw (Qoldan)",
        qTextPlaceholder: "Soraw teksti",
        optAPlaceholder: "Variant A",
        optBPlaceholder: "Variant B",
        optCPlaceholder: "Variant C",
        optDPlaceholder: "Variant D",
        lblCorrect: "Durıs juwap:",
        optA: "Variant A",
        optB: "Variant B",
        optC: "Variant C",
        optD: "Variant D",
        lblPoints: "Soraw ballı:",
        saveQBtn: "Sorawdı saqlaw",
        wordImportTitle: "Word fayldan juklew (.docx)",
        wordImportHint: "Word faylıńız tómendegi shablonǵa sáykes keliwi kerek:",
        btnImport: "Sorawlardı import qılıw",
        questionsListTitle: "Barlıq sorawlar",
        resultsTableTitle: "Natiyjeler keste",
        lblFilterClass: "Klass boyınsha filter:",
        filterAll: "Barlıǵı",
        btnExportCsv: "Excel formatında juklep alıw (CSV)",
        btnClearResults: "Barlıq natiyjelerdi tazalaw",
        thScore: "Toplanǵan ball",
        thPercent: "Procent",
        thBlocks: "Bloklar sanı",
        settingsGeneralTitle: "Test ulıwma sazlamaları",
        lblTestDuration: "Test waqtı (minutta):",
        settingsTelegramTitle: "Telegram bot sazlamaları (Xabarlandırıw hám rezerv)",
        settingsTelegramHint: "Hár bir oqıwshı testti juwmaqlaǵannan keyin, onıń natiyjeleri Telegram arqalı sizge jiberiledi.",
        lblTgBotToken: "Telegram Bot Token:",
        lblTgChatId: "Telegram Chat ID (Gruppa yamasa jeke ID):",
        btnSaveSettings: "Barlıq sazlamalardı saqlaw",
        qrTitle: "Proekt QR-kodı",
        qrHint: "Usı QR-kod járdeminde oqıwshılar testke tez kiriwi múmkin.",
        downloadQr: "QR-kodtı juklep alıw (PNG)",
        quizInfoQuestion: "Soraw",
        quizInfoPoints: "ball",
        nextBtn: "Keyingi soraw",
        testFinishedTitle: "Test Juwmaqlandı",
        certCongrats: "Qutlıqlaymız! Siz joqarı natiyje kórsettińiz.",
        certInfo: "Siz óz sertifikatıńızdı juklep alıwıńız múmkin.",
        btnDownloadCert: "Sertifikattı juklep alıw (PNG)",
        errorReviewTitle: "Qáteler ústinde islew",
        btnBackToHome: "Tiykarǵı betke qaytıw",
        lockWarningTitle: "SİZ BLOKLANDIŃIZ!",
        lockWarningText: "Sistemadan paydalanıw qaǵıydaları buzıldı (ekran ózgertildi yamasa tolıq ekran rejiminen shıǵıldı).",
        lockAdminNote: "Bloktan shıǵarıw ushın admin parolın kiritiń:",
        lockPassPlaceholder: "Admin paroli",
        lockBtnUnlock: "Bloktan shıǵarıw",

        alertDuration: "İltimas, test waqtın durıs kiritiń!",
        teacherPinSaved: "Siziń pánińiz ushın sazlawlar tabıslı saqlandı!",
        teacherTimerPrefix: "Siziń ruxsatnamańız tawsılıwına qaldı:",
        teacherTimerMins: "minut",
        teacherTimerSecs: "sekund",
        adminLoginLink: "Mug'allimler hám Admin kiriwi",
        backToStudentLogin: "Oqıwshı aynasına qaytıw",
        teacherPinSetterTitle: "Pánińiz ushın PIN-kod hám Test waqtın belgileń",
        lblTeacherPin: "Oqıwshılar ushın PIN-kod:",
        lblTeacherDuration: "Test dawamlılıǵı (minut):",
        btnSaveTeacherSettings: "Sazlawlardı saqlaw",
        timeUpAlert: "Siziń waqtınshalıq ruxsatnamańız óz juwmaǵına jetti!",
        alertDetails: "İltimas, isimińiz hám klassıńızdı tolıq kiritiń!",
        alertNoQuestions: "Sorawlar tabılmadı! İltimas, admin menen baylanısıń.",
        alertFields: "Barlıq maydanlardı toltırıń!",
        alertAdded: "Soraw qosıldı!",
        alertSelectFile: "İltimas, dáslep Word (.docx) faylın saylań!",
        alertReadError: "Fayldı oqıwda qátelik júz berdi!",
        alertConfirmClear: "Natiyjelerdi pútkilley óshirmekshisiz be?",
        alertNoExport: "Eksport qılıw ushın natiyjeler tabılmadı!",
        alertImportEmpty: "Fayl ishinen sáykes formattaǵı sorawlar tabılmadı! İltimas shablondı tekseriń.",
        alertConfirmDelete: "Usı sorawdı óshirmekshisiz be?",
        alertTimeout: "Waqıt tawsıldı! Test avtomatikalıq túrde juwmaqlanadı.",
        alertImportSuccess: "Tabıslı juklendi:",
        alertImportSuccess2: "ta taza soraw qosıldı!",
        btnDelete: "Óshiriw",
        unknown: "Belgisiz",
        times: "márte",
        noResults: "Házirshe natiyjeler tabılmadı.",
        emptyLeaderboard: "Reyting kestesi bos.",
        notAnswered: "Juwap berilmegen",
        yourAnswer: "Siz saylaǵan juwap:",
        noMistakes: "Qutlıqlaymız! Hech qanday qátege jol qoyılmadı.",
        studentLabel: "Oqıwshı:",
        percentageLabel: "Procent kóretkishi:",
        timeSpent: "Sarp etilgen waqıt:",
        violations: "Qaǵıyda buzıwshılıqlar (Bloklar):",
        analysisLabel: "Analiz:",
        totalLimit: "Ulıwma limit:",
        min: "min",
        certTitle: "HÚRMET JARLÍǴÍ",
        certGivenTo: "Usı sertifikat tapsırıladı:",
        studentOfClass: "-klass oqıwshısı",
        certText1: "Portalımızdaǵı imtixannan joqarı natiyje",
        certText2: "arnawlı pánler boyınsha bekkem bilimin kórsetkeni ushın.",
        dateLabel: "Sáne:",
        portalAdmin: "Portal Hákimshiligi",
        examResult: "İMTİXAN NATİYJESİ",
        analysisEx: "Úlgi dáreje! Siz temanı tolıq ózlestirgensiz.",
        analysisGood: "Jaqsı natiyje. Bilimińizdi jáne de bekkemlewińiz múmkin.",
        analysisSat: "Qanaatlandararlıq. Tákirarlaw kóbirek talap etiledi.",
        analysisBad: "Tómen natiyje. İltimas, sabaqlıqtı qaytadan oqıp shıǵıń.",
        lblFilterQuarter: "Sherek:",
        qAll: "Barlıq shedrekler",
        q1: "I shedrek",
        q2: "II shedrek",
        q3: "III shedrek",
        q4: "IV shedrek",
        analyticsTitle: "Shedrek taldawı (Kognitiv dárejeler)",
        lblCognitive: "Kognitiv dáreje:",
        statTotalStudents: "Oqıwshılar sanı",
        statAvgScore: "Ortasha kórsetkish (%)",
        statQuality: "Sapa kórsetkishi (70%+)",
        lblQFormat: "Soraw formatı:",
        fmtClosed: "Jabıq test (A,B,C,D)",
        fmtOpen: "Ashıq soraw (Jazbasha)",
        lblOpenAnswer: "Durıs juwap teksti (Gilt sóz):",
        phOpenAnswer: "Juवाबıńızdı kiritıń...",
        lblWritten: "Jazbasha",
        comparisonTitle: "Eki sherekti óz-ara analiz qılıw",
        btnCompare: "Analiz qılıw",
        compIncreased: "ǵa ÓSTİ",
        compDecreased: "ǵa PÁSAYDÍ",
        compSame: "ÓZGERİSSİZ qaldı",
        compConclusion: "Pedagogikalıq analiz:",
        compConclusionGood: "Jaqsı natiyje, qosımsha sabaqlar óz paydasın bermekte.",
        compConclusionBad: "Qáweterli jaǵday, ózlestiriw tómenlegen. Qosımsha ilajlar kóriw zárúr.",
        compConclusionNeutral: "Ózlestiriw turaqlı, biraq ósiw ústinde islew usınıs etiledi.",
        subjectPlaceholder: "Pándi tańlań",
        pinPlaceholder: "Arnawlı PIN-kodtı kiritiń",
        subjOnaTili: "Ana tili",
        subjMatematika: "Matematika",
        subjFizika: "Fizika",
        subjKimyo: "Ximiya",
        subjBiologiya: "Biologiya",
        subjTarix: "Tariyx",
        subjHuquq: "Huqıq",
        subjInformatika: "Informatika",
        settingsPinsTitle: "Pánler hám PIN-kodlar",
        settingsPinsHint: "Oqıwshılar testti baslawı ushın hár bir pánge arnawlı PIN-kod ornatıń.",
        settingsGeminiTitle: "Gemini AI Sazlamaları",
        settingsGeminiHint: "Pedagogik analiz ótkiziw ushın Google Gemini API giltin kiritiń.",
        lblGeminiKey: "Gemini AI API Gilti:",
        btnAnalyzeAI: "Gemini AI analizi ✨",
        aiAnalyzing: "Gemini AI klas natiyjelerin hám kognitiv dárejelerin analiz etip atır...",
        btnCloseAI: "Nátiyjeni jabıw",
        aiAnalysisTitle: "Gemini AI Analizi",
        thSubject: "Pәn",
        alertWrongPin: "Qáte! Bul pán ushın PIN-kod qáte kiritildi.",
        alertGeminiNoKey: "Qáte! Iltimas, Sazlamalar bóliminen Gemini API giltin kiritiń.",
        geminiLoading: "Gemini AI analiz qılmaqta, iltimas kútiń...",
        lblTestType: "Test túri:",
        testTypeBSB: "BBYb",
        testTypeCHSB: "ChBYb",
        lblUploadImage: "Súvret júklew",
        instructionRules: "Test islew qağıydaları:",
        rule1: "Testti baslağannan soń waqıt artqa esaplanıp baslaydı.",
        rule2: "Betti jańalaw (Refresh) yamasa jabıw qadağan etiledi (nátiyje joğalıwı múmkin).",
        rule2: "Betti jańalaw (Refresh) yamasa jabıw qadağan etiledi (nátiyje joğalıwı múmkin).",
        rule3: "Jabıq testlerde tek bir durıs juwaptı belgileń, ashıq sawallarda bolsa juwaptı klaviaturada qolda jazıń.",
        btnBeginTest: "Testti baslaw",
        lblTime: "Waqıt:",
        lblCount: "Sawallar sanı:"
    },
    en: {
        toastWarning: "Viewing code is prohibited due to system security!",
        schoolName: "Khodjeyli specialized school",
        welcomeMsg: "Welcome! Enter your details to start the test.",
        namePlaceholder: "Full Name",
        classPlaceholder: "Class / Group (e.g., 9-A, 11-B)",
        pinPlaceholder: "Enter specific PIN code",
        cogKnowing: "Knowing / Knowledge",
        cogApp: "Application",
        cogReasoning: "Reasoning",
        selClass: "Select Class",
        selQuarter: "Select Quarter",
        btnExportExcel: "Download as Excel (SA/TSA)",
        startBtn: "Start Test",
        adminLoginBtn: "Admin Login",
        leaderboardTitle: "🏆 Top-10 Leaderboard",
        thRank: "Rank",
        thName: "Name",
        thClass: "Class",
        thPoints: "Points",
        thTime: "Time",
        adminModalTitle: "Admin System Login",
        adminPassPlaceholder: "Enter Admin Password",
        adminModalSubmit: "Login",
        adminModalCancel: "Cancel",
        incorrectPass: "Incorrect password!",
        adminPanelTitle: "Admin Control Panel",
        adminLogoutBtn: "Close Panel",
        tabQuestions: "Questions Management",
        tabResults: "Student Results",
        tabSettings: "Settings",
        tabQr: "Get QR Code",
        tabSecurity: "Security",
        secTitle: "Security Settings",
        secShowAnswersTitle: "Show answers in results",
        secShowAnswersDesc: "Will the student be able to see the list of correct answers to the questions they got wrong at the end of the test?",
        hiddenAnswersMsg: "Correct answers are hidden for security reasons.",
        settingsTeachersTitle: "Temporary permissions for teachers",
        settingsTeachersHint: "Generate a temporary password (token) so teachers can add questions and view results for their subject.",
        lblTeacherName: "Teacher Full Name:",
        lblTeacherSubject: "Select Subject:",
        lblTeacherExpire: "Expiration time:",
        exp2h: "2 hours",
        exp1d: "1 day",
        exp1w: "1 week",
        exp1m: "1 month",
        btnGenerateToken: "Generate Password",
        thTeacherName: "Full Name",
        thTeacherSubject: "Subject",
        thTeacherToken: "Token",
        thTeacherExpire: "Expires At",
        thTeacherAction: "Action",
        alertTokenExpired: "This password has expired!",
        manualAddTitle: "Add New Question (Manual)",
        qTextPlaceholder: "Question text",
        optAPlaceholder: "Option A",
        optBPlaceholder: "Option B",
        optCPlaceholder: "Option C",
        optDPlaceholder: "Option D",
        lblCorrect: "Correct answer:",
        optA: "Option A",
        optB: "Option B",
        optC: "Option C",
        optD: "Option D",
        lblPoints: "Question points:",
        saveQBtn: "Save Question",
        wordImportTitle: "Upload from Word (.docx)",
        wordImportHint: "Your Word file must match the following template:",
        btnImport: "Import Questions",
        questionsListTitle: "Available Questions",
        resultsTableTitle: "Results Table",
        lblFilterClass: "Filter by Class:",
        filterAll: "All",
        btnExportCsv: "Export as Excel (CSV)",
        btnClearResults: "Clear All Results",
        thScore: "Score",
        thPercent: "Percentage",
        thBlocks: "Blocks",
        settingsGeneralTitle: "General Test Settings",
        lblTestDuration: "Test Duration (minutes):",
        settingsTelegramTitle: "Telegram Bot Settings (Notifications & Backup)",
        settingsTelegramHint: "After each student finishes the test, their results will be sent to you via Telegram.",
        lblTgBotToken: "Telegram Bot Token:",
        lblTgChatId: "Telegram Chat ID (Group or Personal ID):",
        btnSaveSettings: "Save All Settings",
        qrTitle: "Project QR Code",
        qrHint: "Students can quickly access the test using this QR code.",
        downloadQr: "Download QR Code (PNG)",
        quizInfoQuestion: "Question",
        quizInfoPoints: "points",
        nextBtn: "Next Question",
        testFinishedTitle: "Test Finished",
        certCongrats: "Congratulations! You achieved a high score.",
        certInfo: "You can download your certificate.",
        btnDownloadCert: "Download Certificate (PNG)",
        errorReviewTitle: "Review Mistakes",
        btnBackToHome: "Back to Home",
        lockWarningTitle: "YOU ARE BLOCKED!",
        lockWarningText: "System usage rules were violated (screen changed or exited fullscreen mode).",
        lockAdminNote: "Enter admin password to unlock:",
        lockPassPlaceholder: "Admin Password",
        lockBtnUnlock: "Unlock",
        
        alertDuration: "Please enter a valid test duration!",
        teacherPinSaved: "Settings for your subject have been saved successfully!",
        teacherTimerPrefix: "Your temporary permission expires in:",
        teacherTimerMins: "minutes",
        teacherTimerSecs: "seconds",
        adminLoginLink: "Teacher and Admin Login",
        backToStudentLogin: "Back to Student Screen",
        teacherPinSetterTitle: "Set PIN Code and Test Time for your subject",
        lblTeacherPin: "PIN Code for students:",
        lblTeacherDuration: "Test duration (minutes):",
        btnSaveTeacherSettings: "Save Settings",
        timeUpAlert: "Your temporary permission has expired!",
        alertDetails: "Please enter your full name and class!",
        alertNoQuestions: "No questions available! Please contact the admin.",
        alertFields: "Fill in all fields!",
        alertAdded: "Question added!",
        alertSelectFile: "Please select a Word (.docx) file first!",
        alertReadError: "Error reading the file!",
        alertConfirmClear: "Are you sure you want to completely clear all results?",
        alertNoExport: "No results available to export!",
        alertImportEmpty: "No questions matching the format were found in the file! Please check the template.",
        alertConfirmDelete: "Are you sure you want to delete this question?",
        alertTimeout: "Time's up! The test will automatically finish.",
        alertImportSuccess: "Successfully loaded:",
        alertImportSuccess2: "new questions added!",
        btnDelete: "Delete",
        unknown: "Unknown",
        times: "times",
        noResults: "No results available yet.",
        emptyLeaderboard: "Leaderboard is empty.",
        notAnswered: "Not answered",
        yourAnswer: "Your answer:",
        noMistakes: "Congratulations! No mistakes were made.",
        studentLabel: "Student:",
        percentageLabel: "Percentage:",
        timeSpent: "Time spent:",
        violations: "Violations (Blocks):",
        analysisLabel: "Analysis:",
        totalLimit: "Total limit:",
        min: "min",
        certTitle: "CERTIFICATE OF ACHIEVEMENT",
        certGivenTo: "This certificate is awarded to:",
        studentOfClass: "student of class",
        certText1: "For achieving a high score",
        certText2: "in the examination and demonstrating strong knowledge.",
        dateLabel: "Date:",
        portalAdmin: "Portal Administration",
        examResult: "EXAM RESULT",
        analysisEx: "Excellent! You have mastered the subject perfectly.",
        analysisGood: "Good result. You can further consolidate your knowledge.",
        analysisSat: "Satisfactory. More revision is required.",
        analysisBad: "Low result. Please review the textbook again.",
        lblFilterQuarter: "Quarter:",
        qAll: "All quarters",
        q1: "I quarter",
        q2: "II quarter",
        q3: "III quarter",
        q4: "IV quarter",
        analyticsTitle: "Quarterly Analytics (Cognitive Levels)",
        lblCognitive: "Cognitive level:",
        statTotalStudents: "Total Students",
        statAvgScore: "Average Score (%)",
        statQuality: "Quality Indicator (70%+)",
        lblQFormat: "Question format:",
        fmtClosed: "Closed test (A,B,C,D)",
        fmtOpen: "Open question (Written)",
        lblOpenAnswer: "Correct answer text (Keyword):",
        phOpenAnswer: "Enter your answer...",
        lblWritten: "Written",
        comparisonTitle: "Compare Two Quarters",
        btnCompare: "Analyze",
        compIncreased: "INCREASED by",
        compDecreased: "DECREASED by",
        compSame: "remained UNCHANGED",
        compConclusion: "Pedagogical Conclusion:",
        compConclusionGood: "Good result, additional lessons are showing positive effects.",
        compConclusionBad: "Concerning situation, individual work with students is required.",
        compConclusionNeutral: "No change, efforts need to be increased.",
        subjectPlaceholder: "Select Subject",
        pinPlaceholder: "Enter specific PIN code",
        subjOnaTili: "Native Language",
        subjMatematika: "Mathematics",
        subjFizika: "Physics",
        subjKimyo: "Chemistry",
        subjBiologiya: "Biology",
        subjTarix: "History",
        subjHuquq: "Law",
        subjInformatika: "Informatics",
        settingsPinsTitle: "Subjects and PIN Codes",
        settingsPinsHint: "Set a specific PIN code for each subject to allow students to start the test.",
        settingsGeminiTitle: "Gemini AI Settings",
        settingsGeminiHint: "Enter your Google Gemini API key to run pedagogical analysis.",
        lblGeminiKey: "Gemini AI API Key:",
        btnAnalyzeAI: "Gemini AI Analysis ✨",
        aiAnalyzing: "Gemini AI is analyzing class results and cognitive levels...",
        btnCloseAI: "Close Result",
        aiAnalysisTitle: "Gemini AI Analysis",
        thSubject: "Subject",
        alertWrongPin: "Error! Incorrect PIN code for this subject.",
        alertGeminiNoKey: "Error! Please enter the Gemini API key in the Settings section.",
        geminiLoading: "Gemini AI is analyzing, please wait...",
        lblTestType: "Test Type:",
        testTypeBSB: "SA (Summative Assessment)",
        testTypeCHSB: "TSA (Term Summative Assessment)",
        lblUploadImage: "Upload Image",
        instructionRules: "Test Rules:",
        rule1: "The timer will start counting down once you begin the test.",
        rule2: "Refreshing or closing the page is prohibited (results may be lost).",
        rule2: "Refreshing or closing the page is prohibited (results may be lost).",
        rule3: "For multiple-choice questions, select only one correct answer. For open questions, type your answer using the keyboard.",
        btnBeginTest: "Start Test",
        lblTime: "Time:",
        lblCount: "Question count:"
    }
};

let currentLang = localStorage.getItem('quiz_lang') || 'uz';

function t(key) {
    return translations[currentLang][key] || key;
}

function applyTranslations() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[currentLang] && translations[currentLang][key]) {
            el.innerHTML = translations[currentLang][key];
        }
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (translations[currentLang] && translations[currentLang][key]) {
            el.setAttribute('placeholder', translations[currentLang][key]);
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    applyTranslations();

    const langBtns = document.querySelectorAll('.lang-btn');
    langBtns.forEach(btn => {
        if (btn.getAttribute('data-lang') === currentLang) {
            btn.classList.add('active');
        } else {
            btn.classList.remove('active');
        }

        btn.addEventListener('click', (e) => {
            langBtns.forEach(b => b.classList.remove('active'));
            e.target.classList.add('active');
            currentLang = e.target.getAttribute('data-lang');
            localStorage.setItem('quiz_lang', currentLang);
            applyTranslations();
            
            // Re-render components if methods are available in global scope
            if (typeof renderLeaderboard === 'function' && !document.getElementById('auth-screen').classList.contains('hidden')) {
                renderLeaderboard();
            }
            if (typeof renderQuestionsList === 'function' && !document.getElementById('admin-panel').classList.contains('hidden')) {
                renderQuestionsList();
                if (typeof renderResultsTable === 'function' && document.getElementById('filter-class')) {
                    renderResultsTable(document.getElementById('filter-class').value);
                }
            }
        });
    });
});
